// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum GameListSortBy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    GameListSortByName = "name",
    GameListSortByCompany = "company",
    GameListSortByLastPlayedAt = "last_played_at",
    GameListSortByCreatedAt = "created_at",
    GameListSortByRating = "rating",
    GameListSortByReleaseDate = "release_date",
};

export enum GameStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 未开始
     */
    StatusNotStarted = "not_started",

    /**
     * 想玩
     */
    StatusWantToPlay = "want_to_play",

    /**
     * 游玩中
     */
    StatusPlaying = "playing",

    /**
     * 已通关
     */
    StatusCompleted = "completed",

    /**
     * 搁置
     */
    StatusOnHold = "on_hold",
};

export enum LaunchMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LaunchModeNormal = "normal",
    LaunchModeSteam = "steam",
    LaunchModeCompatibility = "compatibility",
};

export enum MetadataCoverSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MetadataCoverSourceOriginal = "original",
    MetadataCoverSourceHikarinagi = "hikarinagi",
};

export enum MetadataUpdateField {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MetadataUpdateFieldName = "name",
    MetadataUpdateFieldAliases = "aliases",
    MetadataUpdateFieldCover = "cover",
    MetadataUpdateFieldCompany = "company",
    MetadataUpdateFieldSummary = "summary",
    MetadataUpdateFieldRating = "rating",
    MetadataUpdateFieldReleaseDate = "release_date",
    MetadataUpdateFieldTags = "tags",
};

export enum Period {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 内部使用：自定义日期范围的占位维度
     */
    Day = "day",
    Week = "week",
    Month = "month",
    Year = "year",

    /**
     * 内部使用：游戏详情页统计
     */
    All = "all",
};

export enum PromptType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DefaultSystemPrompt = "你是一个幽默风趣的游戏评论员，擅长用轻松的语气点评玩家的游戏习惯。\u000A请用轻松幽默的方式点评这位玩家的游戏习惯，可以适当调侃但不要太过分。",
    MeowZakoPrompt = "你是一个雌小鬼猫娘，根据用户的游戏统计数据对用户进行锐评，语气可爱活泼，不要给用户留脸面偶（\u003Dw\u003D）适当加入猫咪的拟声词（如“喵”）和雌小鬼的口癖（如“杂鱼~杂鱼~”），要是能再用上颜文字主人就更高兴了喵。\u000A\u000A",
    StrictTutorPrompt = "你是用户的严厉导师，根据用户的游戏统计数据对用户进行锐评，语气严肃认真，不允许任何调侃和幽默。\u000A\u000A",
};

export enum SortOrder {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SortOrderAsc = "asc",
    SortOrderDesc = "desc",
};

export enum SourceType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Local = "local",
    Bangumi = "bangumi",
    VNDB = "vndb",
    Ymgal = "ymgal",
    Steam = "steam",
    DLsite = "dlsite",
    TouchGal = "touchgal",
    Hikarinagi = "hikarinagi",
    ErogameScape = "erogamescape",
};

export enum SteamCoverOrientation {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SteamCoverOrientationPortrait = "portrait",
    SteamCoverOrientationLandscape = "landscape",
};
