// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum GameStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 未开始
     */
    StatusNotStarted = "not_started",

    /**
     * 游玩中
     */
    StatusPlaying = "playing",

    /**
     * 已通关
     */
    StatusCompleted = "completed",

    /**
     * 搁置
     */
    StatusOnHold = "on_hold",
};

export enum Period {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Day = "day",
    Week = "week",
    Month = "month",
    All = "all",
};

export enum SourceType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Local = "local",
    Bangumi = "bangumi",
    VNDB = "vndb",
    Ymgal = "ymgal",
};
