// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../common/enums/models.js";

/**
 * AppConfig 应用配置结构体
 */
export class AppConfig {
    "access_token"?: string;
    "bangumi_refresh_token"?: string;
    "bangumi_token_expires_at"?: string;
    "bangumi_authorized_user_id"?: string;
    "bangumi_authorized_username"?: string;
    "bangumi_authorized_avatar_url"?: string;
    "bangumi_auth_error"?: string;
    "bangumi_status_push_enabled"?: boolean | null;
    "hikarinagi_access_token"?: string;
    "hikarinagi_refresh_token"?: string;
    "hikarinagi_token_expires_at"?: string;
    "hikarinagi_authorized_user_id"?: string;
    "hikarinagi_authorized_username"?: string;
    "hikarinagi_authorized_avatar_url"?: string;
    "hikarinagi_auth_error"?: string;
    "hikarinagi_status_push_enabled"?: boolean | null;
    "vndb_access_token"?: string;

    /**
     * 元数据拉取来源列表（bangumi/vndb/ymgal/steam/dlsite/touchgal/hikarinagi/erogamescape）
     */
    "metadata_sources"?: string[];

    /**
     * 批量/外部导入时允许相同 source_type + source_id
     */
    "allow_duplicate_metadata_import": boolean;

    /**
     * Bangumi 封面来源
     */
    "bangumi_cover_source"?: enums$0.MetadataCoverSource;

    /**
     * VNDB 封面来源
     */
    "vndb_cover_source"?: enums$0.MetadataCoverSource;

    /**
     * Steam 封面方向
     */
    "steam_cover_orientation"?: enums$0.SteamCoverOrientation;

    /**
     * light or dark
     */
    "theme": string;

    /**
     * zh, en, etc.
     */
    "language": string;

    /**
     * 侧边栏是否展开
     */
    "sidebar_open": boolean;

    /**
     * 关闭时最小化到托盘
     */
    "close_to_tray": boolean;

    /**
     * AI 配置
     * openai, deepseek, etc.
     */
    "ai_provider"?: string;

    /**
     * API base URL
     */
    "ai_base_url"?: string;

    /**
     * API key
     */
    "ai_api_key"?: string;

    /**
     * model name
     */
    "ai_model"?: string;

    /**
     * AI 系统提示语
     */
    "ai_system_prompt"?: string;

    /**
     * AI 高级配置（防剧透 / WebSearch / 上下文）
     * none | mild | full，全局防剧透默认等级
     */
    "ai_spoiler_level"?: string;

    /**
     * 是否启用 WebSearch 工具调用
     */
    "ai_web_search": boolean;

    /**
     * 送入的历史 session 数量上限（0=默认10）
     */
    "ai_context_window"?: number;

    /**
     * Tavily Search API Key（WebSearch）
     */
    "tavily_api_key"?: string;

    /**
     * 是否启用 GUI 内嵌 MCP HTTP 服务
     */
    "mcp_enabled": boolean;

    /**
     * MCP HTTP 服务监听端口（仅绑定 127.0.0.1）
     */
    "mcp_port"?: number;

    /**
     * 云备份配置
     * 是否启用云备份
     */
    "cloud_backup_enabled": boolean;

    /**
     * 云备份提供商: s3, onedrive, umbra, webdav
     */
    "cloud_backup_provider"?: string;

    /**
     * 备份密码（用于生成 user-id 和加密）
     */
    "backup_password"?: string;

    /**
     * 云端用户标识（由备份密码 hash 生成）
     */
    "backup_user_id"?: string;

    /**
     * 是否启用云同步
     */
    "cloud_sync_enabled": boolean;

    /**
     * 是否启用自动云同步（启动时 + 定时）
     */
    "auto_cloud_sync_enabled": boolean;

    /**
     * 定时全量同步间隔（秒）
     */
    "cloud_sync_interval_sec": number;

    /**
     * 上次云同步时间
     */
    "last_cloud_sync_time"?: string;

    /**
     * 上次云同步状态: idle/syncing/success/failed
     */
    "last_cloud_sync_status"?: string;

    /**
     * 上次云同步错误
     */
    "last_cloud_sync_error"?: string;

    /**
     * S3 兼容端点
     */
    "s3_endpoint"?: string;

    /**
     * S3 区域
     */
    "s3_region"?: string;

    /**
     * S3 存储桶
     */
    "s3_bucket"?: string;

    /**
     * S3 Access Key
     */
    "s3_access_key"?: string;

    /**
     * S3 Secret Key
     */
    "s3_secret_key"?: string;

    /**
     * 云端保留备份数量
     */
    "cloud_backup_retention"?: number;

    /**
     * OneDrive OAuth 配置
     * OneDrive Client ID
     */
    "onedrive_client_id"?: string;

    /**
     * OneDrive Refresh Token（OAuth 授权后获得）
     */
    "onedrive_refresh_token"?: string;

    /**
     * WebDAV 配置
     * WebDAV 服务地址（可含子路径）
     */
    "webdav_url"?: string;

    /**
     * WebDAV 用户名
     */
    "webdav_username"?: string;

    /**
     * WebDAV 密码
     */
    "webdav_password"?: string;

    /**
     * Umbra OAuth 配置（token 与设备密钥由 DPAPI 加密存储，不写入配置文件）
     * Umbra 服务地址
     */
    "umbra_base_url"?: string;

    /**
     * 是否已完成 OAuth 与设备注册
     */
    "umbra_authenticated"?: boolean;

    /**
     * 数据库备份
     * 上次数据库备份时间
     */
    "last_db_backup_time"?: string;

    /**
     * 待恢复的数据库备份路径（重启后执行）
     */
    "pending_db_restore"?: string;

    /**
     * 上次全量数据备份时间
     */
    "last_full_backup_time"?: string;

    /**
     * 待恢复的全量数据备份路径（重启后执行）
     */
    "pending_full_restore"?: string;

    /**
     * 自动备份配置
     * 退出时自动备份数据库
     */
    "auto_backup_db": boolean;

    /**
     * 游戏退出时自动备份存档
     */
    "auto_backup_game_save": boolean;

    /**
     * 已弃用，保留用于配置迁移
     */
    "auto_upload_to_cloud"?: boolean;

    /**
     * 自动上传数据库备份到云端
     */
    "auto_upload_db_to_cloud": boolean;

    /**
     * 自动上传游戏存档备份到云端
     */
    "auto_upload_game_save_to_cloud": boolean;

    /**
     * 备份保留策略
     * 本地游戏备份保留数量
     */
    "local_backup_retention": number;

    /**
     * 本地数据库备份保留数量
     */
    "local_db_backup_retention": number;

    /**
     * 窗口尺寸记忆
     * 窗口宽度
     */
    "window_width": number;

    /**
     * 窗口高度
     */
    "window_height": number;

    /**
     * 应用界面缩放倍率
     */
    "window_zoom_factor": number;

    /**
     * Windows 登录后自动启动应用
     */
    "launch_at_login": boolean;

    /**
     * 活跃时间追踪配置
     * 仅记录活跃游玩时长（窗口在前台时）
     */
    "record_active_time_only": boolean;

    /**
     * 游戏窗口进入后台时静音
     */
    "mute_game_in_background": boolean;

    /**
     * 启动后检测实际游戏进程的最长等待时间
     */
    "process_detection_timeout_sec": number;

    /**
     * 自动更新配置
     * 启动时自动检查更新
     */
    "check_update_on_startup": boolean;

    /**
     * 自定义更新检查 URL
     */
    "update_check_url"?: string;

    /**
     * 上次更新检查时间
     */
    "last_update_check"?: string;

    /**
     * 跳过的版本号（用户选择忽略的更新）
     */
    "skip_version"?: string;

    /**
     * 背景图配置
     * 自定义背景图路径
     */
    "background_image"?: string;

    /**
     * 背景模糊度 (0-20)
     */
    "background_blur": number;

    /**
     * 背景不透明度 (0-1)
     */
    "background_opacity": number;

    /**
     * 是否启用自定义背景
     */
    "background_enabled": boolean;

    /**
     * 启用自定义背景时隐藏首页游戏封面
     */
    "background_hide_game_cover": boolean;

    /**
     * 启用自定义背景时隐藏首页游戏封面大图
     */
    "background_hide_game_hero_cover": boolean;

    /**
     * 记录自定义背景是不是浅色调
     */
    "background_is_light": boolean;

    /**
     * 首页游戏封面是否自动轮播
     */
    "home_game_carousel_enabled": boolean;

    /**
     * 首页游戏封面轮播间隔（秒）
     */
    "home_game_carousel_interval_sec": number;

    /**
     * Locale Emulator 和 Magpie 配置
     * Locale Emulator 可执行文件路径
     */
    "locale_emulator_path"?: string;

    /**
     * Magpie 可执行文件路径
     */
    "magpie_path"?: string;

    /**
     * macOS/Linux Wine 可执行文件路径
     */
    "wine_runner_path"?: string;

    /**
     * macOS/Linux 默认 WINEPREFIX 或 Proton prefix
     */
    "wine_prefix"?: string;

    /**
     * macOS CrossOver bundle 内的 wine 可执行文件路径
     */
    "crossover_runner_path"?: string;

    /**
     * macOS 默认 CrossOver bottle 名
     */
    "crossover_bottle"?: string;

    /**
     * 时区配置
     * 数据库使用的 IANA 时区名称（如 "Asia/Shanghai"）
     */
    "time_zone"?: string;

    /**
     * 游戏库路径配置
     * 游戏库主目录（下载的游戏将解压到此）
     */
    "game_library_path"?: string;

    /**
     * 批量导入偏好
     * 批量导入扫描预设
     */
    "batch_import_scan_preset"?: string;

    /**
     * 批量导入按目录导入层级
     */
    "batch_import_hierarchy_depth": number;
    "batch_import_preferred_source"?: string;

    /**
     * 网络代理配置
     * 全局网络代理模式：system / manual / direct
     */
    "network_proxy_mode"?: string;

    /**
     * 全局手动代理 URL
     */
    "network_proxy_url"?: string;

    /**
     * Tag 配置
     * 是否在详情页展示 NSFW tag，默认 false
     */
    "show_nsfw_tags": boolean;

    /**
     * 是否显示 VNDB tag 中文翻译，默认 true
     */
    "enable_tag_translation": boolean;

    /**
     * 刮削 tag 数量上限，-1 表示不限制，0 表示不刮削 tag
     */
    "scraped_tag_limit": number;

    /**
     * 游戏卡片显示
     * 游戏库卡片布局：portrait / landscape
     */
    "game_card_layout"?: string;

    /**
     * 是否在游戏卡片封面底部展示当前排序字段对应的值
     */
    "show_sort_field_on_cover": boolean;

    /**
     * 是否模糊 NSFW 游戏封面
     */
    "blur_nsfw_game_covers": boolean;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("allow_duplicate_metadata_import" in $$source)) {
            this["allow_duplicate_metadata_import"] = false;
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("sidebar_open" in $$source)) {
            this["sidebar_open"] = false;
        }
        if (!("close_to_tray" in $$source)) {
            this["close_to_tray"] = false;
        }
        if (!("ai_web_search" in $$source)) {
            this["ai_web_search"] = false;
        }
        if (!("mcp_enabled" in $$source)) {
            this["mcp_enabled"] = false;
        }
        if (!("cloud_backup_enabled" in $$source)) {
            this["cloud_backup_enabled"] = false;
        }
        if (!("cloud_sync_enabled" in $$source)) {
            this["cloud_sync_enabled"] = false;
        }
        if (!("auto_cloud_sync_enabled" in $$source)) {
            this["auto_cloud_sync_enabled"] = false;
        }
        if (!("cloud_sync_interval_sec" in $$source)) {
            this["cloud_sync_interval_sec"] = 0;
        }
        if (!("auto_backup_db" in $$source)) {
            this["auto_backup_db"] = false;
        }
        if (!("auto_backup_game_save" in $$source)) {
            this["auto_backup_game_save"] = false;
        }
        if (!("auto_upload_db_to_cloud" in $$source)) {
            this["auto_upload_db_to_cloud"] = false;
        }
        if (!("auto_upload_game_save_to_cloud" in $$source)) {
            this["auto_upload_game_save_to_cloud"] = false;
        }
        if (!("local_backup_retention" in $$source)) {
            this["local_backup_retention"] = 0;
        }
        if (!("local_db_backup_retention" in $$source)) {
            this["local_db_backup_retention"] = 0;
        }
        if (!("window_width" in $$source)) {
            this["window_width"] = 0;
        }
        if (!("window_height" in $$source)) {
            this["window_height"] = 0;
        }
        if (!("window_zoom_factor" in $$source)) {
            this["window_zoom_factor"] = 0;
        }
        if (!("launch_at_login" in $$source)) {
            this["launch_at_login"] = false;
        }
        if (!("record_active_time_only" in $$source)) {
            this["record_active_time_only"] = false;
        }
        if (!("mute_game_in_background" in $$source)) {
            this["mute_game_in_background"] = false;
        }
        if (!("process_detection_timeout_sec" in $$source)) {
            this["process_detection_timeout_sec"] = 0;
        }
        if (!("check_update_on_startup" in $$source)) {
            this["check_update_on_startup"] = false;
        }
        if (!("background_blur" in $$source)) {
            this["background_blur"] = 0;
        }
        if (!("background_opacity" in $$source)) {
            this["background_opacity"] = 0;
        }
        if (!("background_enabled" in $$source)) {
            this["background_enabled"] = false;
        }
        if (!("background_hide_game_cover" in $$source)) {
            this["background_hide_game_cover"] = false;
        }
        if (!("background_hide_game_hero_cover" in $$source)) {
            this["background_hide_game_hero_cover"] = false;
        }
        if (!("background_is_light" in $$source)) {
            this["background_is_light"] = false;
        }
        if (!("home_game_carousel_enabled" in $$source)) {
            this["home_game_carousel_enabled"] = false;
        }
        if (!("home_game_carousel_interval_sec" in $$source)) {
            this["home_game_carousel_interval_sec"] = 0;
        }
        if (!("batch_import_hierarchy_depth" in $$source)) {
            this["batch_import_hierarchy_depth"] = 0;
        }
        if (!("show_nsfw_tags" in $$source)) {
            this["show_nsfw_tags"] = false;
        }
        if (!("enable_tag_translation" in $$source)) {
            this["enable_tag_translation"] = false;
        }
        if (!("scraped_tag_limit" in $$source)) {
            this["scraped_tag_limit"] = 0;
        }
        if (!("show_sort_field_on_cover" in $$source)) {
            this["show_sort_field_on_cover"] = false;
        }
        if (!("blur_nsfw_game_covers" in $$source)) {
            this["blur_nsfw_game_covers"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        const $$createField17_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata_sources" in $$parsedSource) {
            $$parsedSource["metadata_sources"] = $$createField17_0($$parsedSource["metadata_sources"]);
        }
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
