// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppConfig 应用配置结构体
 */
export class AppConfig {
    "access_token"?: string;
    "vndb_access_token"?: string;

    /**
     * light or dark
     */
    "theme": string;

    /**
     * zh, en, etc.
     */
    "language": string;

    /**
     * 侧边栏是否展开
     */
    "sidebar_open": boolean;

    /**
     * 关闭时最小化到托盘
     */
    "close_to_tray": boolean;

    /**
     * AI 配置
     * openai, deepseek, etc.
     */
    "ai_provider"?: string;

    /**
     * API base URL
     */
    "ai_base_url"?: string;

    /**
     * API key
     */
    "ai_api_key"?: string;

    /**
     * model name
     */
    "ai_model"?: string;

    /**
     * AI 系统提示语
     */
    "ai_system_prompt"?: string;

    /**
     * 云备份配置
     * 是否启用云备份
     */
    "cloud_backup_enabled": boolean;

    /**
     * 云备份提供商: s3, onedrive
     */
    "cloud_backup_provider"?: string;

    /**
     * 备份密码（用于生成 user-id 和加密）
     */
    "backup_password"?: string;

    /**
     * 云端用户标识（由备份密码 hash 生成）
     */
    "backup_user_id"?: string;

    /**
     * S3 兼容端点
     */
    "s3_endpoint"?: string;

    /**
     * S3 区域
     */
    "s3_region"?: string;

    /**
     * S3 存储桶
     */
    "s3_bucket"?: string;

    /**
     * S3 Access Key
     */
    "s3_access_key"?: string;

    /**
     * S3 Secret Key
     */
    "s3_secret_key"?: string;

    /**
     * 云端保留备份数量
     */
    "cloud_backup_retention"?: number;

    /**
     * OneDrive OAuth 配置
     * OneDrive Client ID
     */
    "onedrive_client_id"?: string;

    /**
     * OneDrive Refresh Token（OAuth 授权后获得）
     */
    "onedrive_refresh_token"?: string;

    /**
     * 数据库备份
     * 上次数据库备份时间
     */
    "last_db_backup_time"?: string;

    /**
     * 待恢复的数据库备份路径（重启后执行）
     */
    "pending_db_restore"?: string;

    /**
     * 自动备份配置
     * 退出时自动备份数据库
     */
    "auto_backup_db": boolean;

    /**
     * 游戏退出时自动备份存档
     */
    "auto_backup_game_save": boolean;

    /**
     * 已弃用，保留用于配置迁移
     */
    "auto_upload_to_cloud"?: boolean;

    /**
     * 自动上传数据库备份到云端
     */
    "auto_upload_db_to_cloud": boolean;

    /**
     * 自动上传游戏存档备份到云端
     */
    "auto_upload_game_save_to_cloud": boolean;

    /**
     * 备份保留策略
     * 本地游戏备份保留数量
     */
    "local_backup_retention": number;

    /**
     * 本地数据库备份保留数量
     */
    "local_db_backup_retention": number;

    /**
     * 窗口尺寸记忆
     * 窗口宽度
     */
    "window_width": number;

    /**
     * 窗口高度
     */
    "window_height": number;

    /**
     * 活跃时间追踪配置
     * 仅记录活跃游玩时长（窗口在前台时）
     */
    "record_active_time_only": boolean;

    /**
     * 自动更新配置
     * 启动时自动检查更新
     */
    "check_update_on_startup": boolean;

    /**
     * 自定义更新检查 URL
     */
    "update_check_url"?: string;

    /**
     * 上次更新检查时间
     */
    "last_update_check"?: string;

    /**
     * 跳过的版本号（用户选择忽略的更新）
     */
    "skip_version"?: string;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("sidebar_open" in $$source)) {
            this["sidebar_open"] = false;
        }
        if (!("close_to_tray" in $$source)) {
            this["close_to_tray"] = false;
        }
        if (!("cloud_backup_enabled" in $$source)) {
            this["cloud_backup_enabled"] = false;
        }
        if (!("auto_backup_db" in $$source)) {
            this["auto_backup_db"] = false;
        }
        if (!("auto_backup_game_save" in $$source)) {
            this["auto_backup_game_save"] = false;
        }
        if (!("auto_upload_db_to_cloud" in $$source)) {
            this["auto_upload_db_to_cloud"] = false;
        }
        if (!("auto_upload_game_save_to_cloud" in $$source)) {
            this["auto_upload_game_save_to_cloud"] = false;
        }
        if (!("local_backup_retention" in $$source)) {
            this["local_backup_retention"] = 0;
        }
        if (!("local_db_backup_retention" in $$source)) {
            this["local_db_backup_retention"] = 0;
        }
        if (!("window_width" in $$source)) {
            this["window_width"] = 0;
        }
        if (!("window_height" in $$source)) {
            this["window_height"] = 0;
        }
        if (!("record_active_time_only" in $$source)) {
            this["record_active_time_only"] = false;
        }
        if (!("check_update_on_startup" in $$source)) {
            this["check_update_on_startup"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}
