// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../enums/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class Game {
    "id": string;
    "name": string;
    "cover_url": string;
    "company": string;
    "summary": string;

    /**
     * 启动路径
     */
    "path": string;

    /**
     * 存档目录路径
     */
    "save_path": string;

    /**
     * 游戏状态: not_started, playing, completed, on_hold
     */
    "status": enums$0.GameStatus;

    /**
     * "local", "bangumi", "vndb"
     */
    "source_type": enums$0.SourceType;
    "cached_at": time$0.Time;
    "source_id": string;
    "created_at": time$0.Time;

    /** Creates a new Game instance. */
    constructor($$source: Partial<Game> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("cover_url" in $$source)) {
            this["cover_url"] = "";
        }
        if (!("company" in $$source)) {
            this["company"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("save_path" in $$source)) {
            this["save_path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = enums$0.GameStatus.$zero;
        }
        if (!("source_type" in $$source)) {
            this["source_type"] = enums$0.SourceType.$zero;
        }
        if (!("cached_at" in $$source)) {
            this["cached_at"] = null;
        }
        if (!("source_id" in $$source)) {
            this["source_id"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Game instance from a string or object.
     */
    static createFrom($$source: any = {}): Game {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Game($$parsedSource as Partial<Game>);
    }
}

/**
 * GameBackup 游戏存档备份记录（基于文件系统，不使用数据库）
 */
export class GameBackup {
    /**
     * 备份文件路径（作为唯一标识）
     */
    "path": string;

    /**
     * 文件名
     */
    "name": string;
    "game_id": string;

    /**
     * 备份文件大小（字节）
     */
    "size": number;

    /**
     * 创建时间（来自文件修改时间）
     */
    "created_at": time$0.Time;

    /** Creates a new GameBackup instance. */
    constructor($$source: Partial<GameBackup> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameBackup instance from a string or object.
     */
    static createFrom($$source: any = {}): GameBackup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameBackup($$parsedSource as Partial<GameBackup>);
    }
}

export class PlaySession {
    "id": string;
    "game_id": string;
    "start_time": time$0.Time;
    "end_time": time$0.Time;

    /**
     * seconds
     */
    "duration": number;

    /** Creates a new PlaySession instance. */
    constructor($$source: Partial<PlaySession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("start_time" in $$source)) {
            this["start_time"] = null;
        }
        if (!("end_time" in $$source)) {
            this["end_time"] = null;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaySession instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaySession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaySession($$parsedSource as Partial<PlaySession>);
    }
}

export class User {
    "id": string;
    "created_at": time$0.Time;

    /**
     * "s3" or "docker"
     */
    "default_backup_target": string;

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("default_backup_target" in $$source)) {
            this["default_backup_target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User($$parsedSource as Partial<User>);
    }
}
