// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LaunchOptions defines optional game launch overrides.
 */
export class LaunchOptions {
    "UseLocaleEmulator": boolean | null;
    "UseMagpie": boolean | null;
    "RunAsAdmin": boolean | null;
    "WineRunner": string | null;
    "WineArgs": string | null;
    "WinePrefix": string | null;
    "UseSteam": boolean | null;
    "UseCompatibility": boolean | null;

    /** Creates a new LaunchOptions instance. */
    constructor($$source: Partial<LaunchOptions> = {}) {
        if (!("UseLocaleEmulator" in $$source)) {
            this["UseLocaleEmulator"] = null;
        }
        if (!("UseMagpie" in $$source)) {
            this["UseMagpie"] = null;
        }
        if (!("RunAsAdmin" in $$source)) {
            this["RunAsAdmin"] = null;
        }
        if (!("WineRunner" in $$source)) {
            this["WineRunner"] = null;
        }
        if (!("WineArgs" in $$source)) {
            this["WineArgs"] = null;
        }
        if (!("WinePrefix" in $$source)) {
            this["WinePrefix"] = null;
        }
        if (!("UseSteam" in $$source)) {
            this["UseSteam"] = null;
        }
        if (!("UseCompatibility" in $$source)) {
            this["UseCompatibility"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LaunchOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): LaunchOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LaunchOptions($$parsedSource as Partial<LaunchOptions>);
    }
}
