// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function CreateBackup(arg1:string):Promise<models.GameBackup>;

export function DeleteBackup(arg1:string):Promise<void>;

export function GetBackupDir():Promise<string>;

export function GetGameBackups(arg1:string):Promise<Array<models.GameBackup>>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function OpenBackupFolder(arg1:string):Promise<void>;

export function RestoreBackup(arg1:string):Promise<void>;
