// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackup(arg1) {
  return window['go']['service']['BackupService']['CreateBackup'](arg1);
}

export function CreateDBBackup() {
  return window['go']['service']['BackupService']['CreateDBBackup']();
}

export function DeleteBackup(arg1) {
  return window['go']['service']['BackupService']['DeleteBackup'](arg1);
}

export function DeleteDBBackup(arg1) {
  return window['go']['service']['BackupService']['DeleteDBBackup'](arg1);
}

export function DownloadCloudBackup(arg1, arg2) {
  return window['go']['service']['BackupService']['DownloadCloudBackup'](arg1, arg2);
}

export function GetBackupDir() {
  return window['go']['service']['BackupService']['GetBackupDir']();
}

export function GetCloudBackupStatus() {
  return window['go']['service']['BackupService']['GetCloudBackupStatus']();
}

export function GetCloudGameBackups(arg1) {
  return window['go']['service']['BackupService']['GetCloudGameBackups'](arg1);
}

export function GetDBBackupDir() {
  return window['go']['service']['BackupService']['GetDBBackupDir']();
}

export function GetDBBackups() {
  return window['go']['service']['BackupService']['GetDBBackups']();
}

export function GetGameBackups(arg1) {
  return window['go']['service']['BackupService']['GetGameBackups'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['BackupService']['Init'](arg1, arg2, arg3);
}

export function OpenBackupFolder(arg1) {
  return window['go']['service']['BackupService']['OpenBackupFolder'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['service']['BackupService']['RestoreBackup'](arg1);
}

export function RestoreFromCloud(arg1, arg2) {
  return window['go']['service']['BackupService']['RestoreFromCloud'](arg1, arg2);
}

export function ScheduleDBRestore(arg1) {
  return window['go']['service']['BackupService']['ScheduleDBRestore'](arg1);
}

export function SetupCloudBackup(arg1) {
  return window['go']['service']['BackupService']['SetupCloudBackup'](arg1);
}

export function TestS3Connection(arg1) {
  return window['go']['service']['BackupService']['TestS3Connection'](arg1);
}

export function UploadGameBackupToCloud(arg1, arg2) {
  return window['go']['service']['BackupService']['UploadGameBackupToCloud'](arg1, arg2);
}
