// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackup(arg1) {
  return window['go']['service']['BackupService']['CreateBackup'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['service']['BackupService']['DeleteBackup'](arg1);
}

export function GetBackupDir() {
  return window['go']['service']['BackupService']['GetBackupDir']();
}

export function GetGameBackups(arg1) {
  return window['go']['service']['BackupService']['GetGameBackups'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['BackupService']['Init'](arg1, arg2, arg3);
}

export function OpenBackupFolder(arg1) {
  return window['go']['service']['BackupService']['OpenBackupFolder'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['service']['BackupService']['RestoreBackup'](arg1);
}
