// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Disconnect() {
  return window['go']['service']['BangumiService']['Disconnect']();
}

export function GetAuthStatus() {
  return window['go']['service']['BangumiService']['GetAuthStatus']();
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['BangumiService']['Init'](arg1, arg2, arg3);
}

export function SetEventEmitter(arg1) {
  return window['go']['service']['BangumiService']['SetEventEmitter'](arg1);
}

export function SetHTTPClient(arg1) {
  return window['go']['service']['BangumiService']['SetHTTPClient'](arg1);
}

export function SetNowFunc(arg1) {
  return window['go']['service']['BangumiService']['SetNowFunc'](arg1);
}

export function SetOAuthClientCredentials(arg1, arg2) {
  return window['go']['service']['BangumiService']['SetOAuthClientCredentials'](arg1, arg2);
}

export function SetOpenURLFunc(arg1) {
  return window['go']['service']['BangumiService']['SetOpenURLFunc'](arg1);
}

export function StartAuth() {
  return window['go']['service']['BangumiService']['StartAuth']();
}
