// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Disconnect() {
  return window['go']['service']['BangumiService']['Disconnect']();
}

export function GetAuthStatus() {
  return window['go']['service']['BangumiService']['GetAuthStatus']();
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['BangumiService']['Init'](arg1, arg2, arg3);
}

export function StartAuth() {
  return window['go']['service']['BangumiService']['StartAuth']();
}
