// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vo} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function Disconnect():Promise<vo.BangumiAuthStatus>;

export function GetAuthStatus():Promise<vo.BangumiAuthStatus>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function StartAuth():Promise<vo.BangumiAuthStatus>;
