// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCloudSyncStatus() {
  return window["go"]["service"]["CloudSyncService"]["GetCloudSyncStatus"]();
}

export function Init(arg1, arg2, arg3) {
  return window["go"]["service"]["CloudSyncService"]["Init"](arg1, arg2, arg3);
}

export function NotifyLibraryChanged() {
  return window["go"]["service"]["CloudSyncService"]["NotifyLibraryChanged"]();
}

export function RunStartupSync() {
  return window["go"]["service"]["CloudSyncService"]["RunStartupSync"]();
}

export function SyncNow() {
  return window["go"]["service"]["CloudSyncService"]["SyncNow"]();
}
