// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appconf} from '../models';
import {context} from '../models';
import {sql} from '../models';

export function ExportLogsZip():Promise<string>;

export function GetAppConfig():Promise<appconf.AppConfig>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function OpenDataDirectory():Promise<string>;

export function SafeQuit():Promise<void>;

export function SaveCroppedBackgroundImage(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<string>;

export function SelectAndCropBackgroundImage():Promise<string>;

export function SelectBackgroundImage():Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SetQuitHandler(arg1:any):Promise<void>;

export function SetSuppressInitialWindowShow(arg1:boolean):Promise<void>;

export function ShouldShowMainWindowOnReady():Promise<boolean>;

export function UpdateAppConfig(arg1:appconf.AppConfig):Promise<void>;
