// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {vo} from '../models';
import {context} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function GetDownloadTasks():Promise<Array<service.DownloadTask>>;

export function GetPendingInstall():Promise<vo.InstallRequest>;

export function Init(arg1:context.Context):Promise<void>;

export function SetPendingInstall(arg1:vo.InstallRequest):Promise<void>;

export function StartDownload(arg1:vo.InstallRequest):Promise<string>;
