// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['service']['DownloadService']['CancelDownload'](arg1);
}

export function GetDownloadTasks() {
  return window['go']['service']['DownloadService']['GetDownloadTasks']();
}

export function GetPendingInstall() {
  return window['go']['service']['DownloadService']['GetPendingInstall']();
}

export function Init(arg1) {
  return window['go']['service']['DownloadService']['Init'](arg1);
}

export function SetPendingInstall(arg1) {
  return window['go']['service']['DownloadService']['SetPendingInstall'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['service']['DownloadService']['StartDownload'](arg1);
}
