// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['service']['DownloadService']['CancelDownload'](arg1);
}

export function DeleteDownloadTask(arg1) {
  return window['go']['service']['DownloadService']['DeleteDownloadTask'](arg1);
}

export function GetDownloadTasks() {
  return window['go']['service']['DownloadService']['GetDownloadTasks']();
}

export function GetPendingInstall() {
  return window['go']['service']['DownloadService']['GetPendingInstall']();
}

export function ImportDownloadTaskAsGame(arg1) {
  return window['go']['service']['DownloadService']['ImportDownloadTaskAsGame'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['DownloadService']['Init'](arg1, arg2, arg3);
}

export function OpenDownloadTaskLocation(arg1) {
  return window['go']['service']['DownloadService']['OpenDownloadTaskLocation'](arg1);
}

export function SetGameService(arg1) {
  return window['go']['service']['DownloadService']['SetGameService'](arg1);
}

export function SetPendingInstall(arg1) {
  return window['go']['service']['DownloadService']['SetPendingInstall'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['service']['DownloadService']['StartDownload'](arg1);
}
