// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function DeleteGameProgress(arg1:string):Promise<void>;

export function GetGameProgress(arg1:string):Promise<models.GameProgress>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function ListGameProgresses(arg1:string):Promise<Array<models.GameProgress>>;

export function UpsertGameProgress(arg1:models.GameProgress):Promise<models.GameProgress>;
