// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteGameProgress(arg1) {
  return window["go"]["service"]["GameProgressService"]["DeleteGameProgress"](
    arg1,
  );
}

export function GetGameProgress(arg1) {
  return window["go"]["service"]["GameProgressService"]["GetGameProgress"](
    arg1,
  );
}

export function Init(arg1, arg2, arg3) {
  return window["go"]["service"]["GameProgressService"]["Init"](
    arg1,
    arg2,
    arg3,
  );
}

export function ListGameProgresses(arg1) {
  return window["go"]["service"]["GameProgressService"]["ListGameProgresses"](
    arg1,
  );
}

export function UpsertGameProgress(arg1) {
  return window["go"]["service"]["GameProgressService"]["UpsertGameProgress"](
    arg1,
  );
}
