// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function DeleteGameProgress(arg1:string):Promise<void>;

export function GetGameProgress(arg1:string):Promise<service.GameProgress>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function ListGameProgresses(arg1:string):Promise<Array<service.GameProgress>>;

export function SetCloudSyncService(arg1:service.CloudSyncService):Promise<void>;

export function UpsertGameProgress(arg1:service.GameProgress):Promise<service.GameProgress>;
