// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportFromPotatoVN(arg1) {
  return window['go']['service']['ImportService']['ImportFromPotatoVN'](arg1);
}

export function Init(arg1, arg2, arg3, arg4) {
  return window['go']['service']['ImportService']['Init'](arg1, arg2, arg3, arg4);
}

export function PreviewImport(arg1) {
  return window['go']['service']['ImportService']['PreviewImport'](arg1);
}

export function SelectZipFile() {
  return window['go']['service']['ImportService']['SelectZipFile']();
}
