// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {context} from '../models';

export function GetStatus():Promise<service.PortableSetupStatus>;

export function Init(arg1:context.Context):Promise<void>;

export function RegisterCLIPath():Promise<service.PortableSetupStatus>;

export function RegisterProtocol():Promise<service.PortableSetupStatus>;

export function UnregisterCLIPath():Promise<service.PortableSetupStatus>;

export function UnregisterProtocol():Promise<service.PortableSetupStatus>;
