// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['service']['PortableSetupService']['GetStatus']();
}

export function Init(arg1) {
  return window['go']['service']['PortableSetupService']['Init'](arg1);
}

export function RegisterCLIPath() {
  return window['go']['service']['PortableSetupService']['RegisterCLIPath']();
}

export function RegisterProtocol() {
  return window['go']['service']['PortableSetupService']['RegisterProtocol']();
}

export function UnregisterCLIPath() {
  return window['go']['service']['PortableSetupService']['UnregisterCLIPath']();
}

export function UnregisterProtocol() {
  return window['go']['service']['PortableSetupService']['UnregisterProtocol']();
}
