// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlaySession(arg1, arg2, arg3) {
  return window['go']['service']['StartService']['AddPlaySession'](arg1, arg2, arg3);
}

export function BatchAddPlaySessions(arg1) {
  return window['go']['service']['StartService']['BatchAddPlaySessions'](arg1);
}

export function DeletePlaySession(arg1) {
  return window['go']['service']['StartService']['DeletePlaySession'](arg1);
}

export function GetPlaySessions(arg1) {
  return window['go']['service']['StartService']['GetPlaySessions'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['StartService']['Init'](arg1, arg2, arg3);
}

export function SetBackupService(arg1) {
  return window['go']['service']['StartService']['SetBackupService'](arg1);
}

export function StartGameWithTracking(arg1) {
  return window['go']['service']['StartService']['StartGameWithTracking'](arg1);
}

export function UpdatePlaySession(arg1) {
  return window['go']['service']['StartService']['UpdatePlaySession'](arg1);
}
