// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportStatsImage(arg1) {
  return window['go']['service']['StatsService']['ExportStatsImage'](arg1);
}

export function FetchImageAsBase64(arg1) {
  return window['go']['service']['StatsService']['FetchImageAsBase64'](arg1);
}

export function GetGameStats(arg1) {
  return window['go']['service']['StatsService']['GetGameStats'](arg1);
}

export function GetGlobalPeriodStats(arg1) {
  return window['go']['service']['StatsService']['GetGlobalPeriodStats'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['StatsService']['Init'](arg1, arg2, arg3);
}
