// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vo} from '../models';
import {enums} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function ExportStatsImage(arg1:string):Promise<void>;

export function FetchImageAsBase64(arg1:string):Promise<string>;

export function GetGameStats(arg1:string):Promise<vo.GameDetailStats>;

export function GetGlobalPeriodStats(arg1:enums.Period):Promise<vo.PeriodStats>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;
