// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';
import {vo} from '../models';

export function DeleteTemplate(arg1:string):Promise<void>;

export function ExportRenderedHTML(arg1:string):Promise<void>;

export function GetTemplate(arg1:string):Promise<string>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function ListTemplates():Promise<Array<vo.TemplateInfo>>;

export function OpenTemplatesDir():Promise<void>;

export function PrepareExportData(arg1:vo.PeriodStats,arg2:string):Promise<vo.StatsExportData>;

export function RenderTemplate(arg1:vo.RenderTemplateRequest):Promise<vo.RenderTemplateResponse>;

export function SaveTemplate(arg1:string,arg2:string):Promise<void>;
