// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportRenderedHTML(arg1) {
  return window['go']['service']['TemplateService']['ExportRenderedHTML'](arg1);
}

export function GetTemplate(arg1) {
  return window['go']['service']['TemplateService']['GetTemplate'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['TemplateService']['Init'](arg1, arg2, arg3);
}

export function ListTemplates() {
  return window['go']['service']['TemplateService']['ListTemplates']();
}

export function OpenTemplatesDir() {
  return window['go']['service']['TemplateService']['OpenTemplatesDir']();
}

export function PrepareExportData(arg1, arg2) {
  return window['go']['service']['TemplateService']['PrepareExportData'](arg1, arg2);
}

export function RenderTemplate(arg1) {
  return window['go']['service']['TemplateService']['RenderTemplate'](arg1);
}
