// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlaySession(arg1, arg2, arg3) {
  return window['go']['service']['TimerService']['AddPlaySession'](arg1, arg2, arg3);
}

export function BatchAddPlaySessions(arg1) {
  return window['go']['service']['TimerService']['BatchAddPlaySessions'](arg1);
}

export function DeletePlaySession(arg1) {
  return window['go']['service']['TimerService']['DeletePlaySession'](arg1);
}

export function GetPlaySessions(arg1) {
  return window['go']['service']['TimerService']['GetPlaySessions'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['TimerService']['Init'](arg1, arg2, arg3);
}

export function SetBackupService(arg1) {
  return window['go']['service']['TimerService']['SetBackupService'](arg1);
}

export function StartGameWithTracking(arg1) {
  return window['go']['service']['TimerService']['StartGameWithTracking'](arg1);
}

export function UpdatePlaySession(arg1) {
  return window['go']['service']['TimerService']['UpdatePlaySession'](arg1);
}
