// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {context} from '../models';

export function CheckForUpdates():Promise<service.UpdateCheckResult>;

export function CheckForUpdatesOnStartup():Promise<service.UpdateCheckResult>;

export function Init(arg1:context.Context,arg2:service.ConfigService):Promise<void>;

export function OpenDownloadURL(arg1:string):Promise<void>;

export function SkipVersion(arg1:string):Promise<void>;
