// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['service']['UpdateService']['CheckForUpdates']();
}

export function CheckForUpdatesOnStartup() {
  return window['go']['service']['UpdateService']['CheckForUpdatesOnStartup']();
}

export function Init(arg1, arg2) {
  return window['go']['service']['UpdateService']['Init'](arg1, arg2);
}

export function OpenDownloadURL(arg1) {
  return window['go']['service']['UpdateService']['OpenDownloadURL'](arg1);
}

export function SkipVersion(arg1) {
  return window['go']['service']['UpdateService']['SkipVersion'](arg1);
}
