// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBuildMode() {
  return window['go']['service']['VersionService']['GetBuildMode']();
}

export function GetBuildTime() {
  return window['go']['service']['VersionService']['GetBuildTime']();
}

export function GetFullVersion() {
  return window['go']['service']['VersionService']['GetFullVersion']();
}

export function GetVersion() {
  return window['go']['service']['VersionService']['GetVersion']();
}

export function GetVersionInfo() {
  return window['go']['service']['VersionService']['GetVersionInfo']();
}

export function Init(arg1) {
  return window['go']['service']['VersionService']['Init'](arg1);
}
