// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetBuildMode():Promise<string>;

export function GetBuildTime():Promise<string>;

export function GetFullVersion():Promise<string>;

export function GetVersion():Promise<string>;

export function GetVersionInfo():Promise<Record<string, string>>;

export function Init(arg1:context.Context):Promise<void>;
