// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../common/enums/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";

/**
 * AISummarize 生成AI锐评总结
 */
export function AISummarize(req: vo$0.AISummaryRequest): $CancellablePromise<vo$0.AISummaryResponse> {
    return $Call.ByID(2441663770, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetPromptPresets 返回内置 AI 提示词，并让 Wails v3 为 PromptType 生成绑定。
 */
export function GetPromptPresets(): $CancellablePromise<enums$0.PromptType[]> {
    return $Call.ByID(1864436781).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = vo$0.AISummaryResponse.createFrom;
const $$createType1 = $Create.Array($Create.Any);
