// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../vo/models.js";

/**
 * AISummarize 生成AI锐评总结
 */
export function AISummarize(req: vo$0.AISummaryRequest): $CancellablePromise<vo$0.AISummaryResponse> {
    return $Call.ByID(2441663770, req).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = vo$0.AISummaryResponse.createFrom;
