// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appconf$0 from "../appconf/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../vo/models.js";

/**
 * CreateAndUploadDBBackup 创建数据库备份并上传到云端
 */
export function CreateAndUploadDBBackup(): $CancellablePromise<vo$0.DBBackupInfo | null> {
    return $Call.ByID(318228197).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateBackup 创建游戏存档备份
 */
export function CreateBackup(gameID: string): $CancellablePromise<models$0.GameBackup | null> {
    return $Call.ByID(2311526085, gameID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CreateDBBackup 创建数据库备份（包含 covers 文件夹）
 */
export function CreateDBBackup(): $CancellablePromise<vo$0.DBBackupInfo | null> {
    return $Call.ByID(1398985643).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteBackup 删除备份（参数改为备份路径）
 */
export function DeleteBackup(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(3941192730, backupPath);
}

/**
 * DeleteDBBackup 删除数据库备份
 */
export function DeleteDBBackup(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(2837492688, backupPath);
}

/**
 * DownloadCloudBackup 从云端下载备份
 */
export function DownloadCloudBackup(cloudKey: string, gameID: string): $CancellablePromise<string> {
    return $Call.ByID(3598055478, cloudKey, gameID);
}

/**
 * DownloadCloudDBBackup 从云端下载数据库备份
 * TODO: 前端提供此功能的按钮
 */
export function DownloadCloudDBBackup(cloudKey: string): $CancellablePromise<string> {
    return $Call.ByID(3171093956, cloudKey);
}

/**
 * ExchangeOneDriveCode 用授权码换取 OneDrive token
 */
export function ExchangeOneDriveCode(code: string): $CancellablePromise<string> {
    return $Call.ByID(3107263687, code);
}

/**
 * GetBackupDir 获取备份根目录
 */
export function GetBackupDir(): $CancellablePromise<string> {
    return $Call.ByID(3424793154);
}

/**
 * GetCloudBackupStatus 获取云备份状态
 */
export function GetCloudBackupStatus(): $CancellablePromise<vo$0.CloudBackupStatus> {
    return $Call.ByID(3586917374).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetCloudDBBackups 获取云端数据库备份列表
 */
export function GetCloudDBBackups(): $CancellablePromise<vo$0.CloudBackupItem[]> {
    return $Call.ByID(2214957703).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetCloudGameBackups 获取云端游戏备份列表
 */
export function GetCloudGameBackups(gameID: string): $CancellablePromise<vo$0.CloudBackupItem[]> {
    return $Call.ByID(2938299527, gameID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetDBBackupDir 获取数据库备份目录
 */
export function GetDBBackupDir(): $CancellablePromise<string> {
    return $Call.ByID(1098316844);
}

/**
 * GetDBBackups 获取数据库备份列表
 */
export function GetDBBackups(): $CancellablePromise<vo$0.DBBackupStatus | null> {
    return $Call.ByID(3429105738).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetGameBackups 获取游戏的备份历史（直接读取文件夹，不使用数据库）
 */
export function GetGameBackups(gameID: string): $CancellablePromise<models$0.GameBackup[]> {
    return $Call.ByID(3817794926, gameID).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetOneDriveAuthURL 获取 OneDrive 授权 URL
 */
export function GetOneDriveAuthURL(): $CancellablePromise<string> {
    return $Call.ByID(3691447260);
}

/**
 * OpenBackupFolder 打开备份文件夹
 */
export function OpenBackupFolder(gameID: string): $CancellablePromise<void> {
    return $Call.ByID(3868003897, gameID);
}

/**
 * RestoreBackup 恢复备份到指定时间点（参数改为备份路径）
 */
export function RestoreBackup(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(1433619077, backupPath);
}

/**
 * RestoreFromCloud 从云端恢复备份
 */
export function RestoreFromCloud(cloudKey: string, gameID: string): $CancellablePromise<void> {
    return $Call.ByID(957684424, cloudKey, gameID);
}

/**
 * ScheduleDBRestore 安排数据库恢复（下次启动时执行）
 */
export function ScheduleDBRestore(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(410699654, backupPath);
}

/**
 * ScheduleDBRestoreFromCloud 从云端下载并安排数据库恢复
 */
export function ScheduleDBRestoreFromCloud(cloudKey: string): $CancellablePromise<void> {
    return $Call.ByID(1769435831, cloudKey);
}

/**
 * SetupCloudBackup 设置云备份密码（只能设置一次）
 */
export function SetupCloudBackup(password: string): $CancellablePromise<string> {
    return $Call.ByID(3285131195, password);
}

/**
 * StartOneDriveAuth 启动 OneDrive 授权流程（使用本地回调服务器）
 */
export function StartOneDriveAuth(): $CancellablePromise<string> {
    return $Call.ByID(2675534199);
}

/**
 * TestOneDriveConnection 测试 OneDrive 连接
 */
export function TestOneDriveConnection(config: appconf$0.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(260269571, config);
}

/**
 * TestS3Connection 测试 S3 连接
 */
export function TestS3Connection(config: appconf$0.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(386048853, config);
}

/**
 * UploadDBBackupToCloud 上传数据库备份到云端
 */
export function UploadDBBackupToCloud(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(2563288224, backupPath);
}

/**
 * UploadGameBackupToCloud 上传游戏存档到云端（参数改为 backupPath）
 */
export function UploadGameBackupToCloud(gameID: string, backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(3053588496, gameID, backupPath);
}

// Private type creation functions
const $$createType0 = vo$0.DBBackupInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.GameBackup.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = vo$0.CloudBackupStatus.createFrom;
const $$createType5 = vo$0.CloudBackupItem.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = vo$0.DBBackupStatus.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType2);
