// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";

export function Disconnect(): $CancellablePromise<vo$0.BangumiAuthStatus> {
    return $Call.ByID(3081268836).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetAuthStatus(): $CancellablePromise<vo$0.BangumiAuthStatus> {
    return $Call.ByID(108553198).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetProfile(): $CancellablePromise<vo$0.BangumiProfile> {
    return $Call.ByID(1724367731).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StartAuth(): $CancellablePromise<vo$0.BangumiAuthStatus> {
    return $Call.ByID(713098480).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SyncAllGameStatuses(): $CancellablePromise<vo$0.RemoteStatusSyncProgress> {
    return $Call.ByID(3929253992).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = vo$0.BangumiAuthStatus.createFrom;
const $$createType1 = vo$0.BangumiProfile.createFrom;
const $$createType2 = vo$0.RemoteStatusSyncProgress.createFrom;
