// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appconf$0 from "../appconf/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../vo/models.js";

export function AddCategory(name: string): $CancellablePromise<void> {
    return $Call.ByID(96734224, name);
}

export function AddGameToCategory(gameID: string, categoryID: string): $CancellablePromise<void> {
    return $Call.ByID(2869666819, gameID, categoryID);
}

export function DeleteCategory(id: string): $CancellablePromise<void> {
    return $Call.ByID(1373643822, id);
}

export function GetCategories(): $CancellablePromise<vo$0.CategoryVO[]> {
    return $Call.ByID(1785011151).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetCategoriesByGame(gameID: string): $CancellablePromise<vo$0.CategoryVO[]> {
    return $Call.ByID(2732097256, gameID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetCategoryByID(id: string): $CancellablePromise<vo$0.CategoryVO> {
    return $Call.ByID(2287025583, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetGamesByCategory(categoryID: string): $CancellablePromise<models$0.Game[]> {
    return $Call.ByID(1277058931, categoryID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Init(db: sql$0.DB | null, config: appconf$0.AppConfig | null): $CancellablePromise<void> {
    return $Call.ByID(3330312415, db, config);
}

export function RemoveGameFromCategory(gameID: string, categoryID: string): $CancellablePromise<void> {
    return $Call.ByID(2468876459, gameID, categoryID);
}

// Private type creation functions
const $$createType0 = vo$0.CategoryVO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.Game.createFrom;
const $$createType3 = $Create.Array($$createType2);
