// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";

export function GetCloudSyncStatus(): $CancellablePromise<vo$0.CloudSyncStatus> {
    return $Call.ByID(31011959).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RunStartupSync(): $CancellablePromise<void> {
    return $Call.ByID(3952022258);
}

export function StartScheduledSync(): $CancellablePromise<void> {
    return $Call.ByID(537075623);
}

export function StopScheduledSync(): $CancellablePromise<void> {
    return $Call.ByID(253775729);
}

export function SyncNow(): $CancellablePromise<vo$0.CloudSyncStatus> {
    return $Call.ByID(1737241588).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = vo$0.CloudSyncStatus.createFrom;
