// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appconf$0 from "../appconf/models.js";

export function GetAppConfig(): $CancellablePromise<appconf$0.AppConfig> {
    return $Call.ByID(1842078622).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SafeQuit 安全退出应用（绕过托盘最小化逻辑）
 */
export function SafeQuit(): $CancellablePromise<void> {
    return $Call.ByID(1997131465);
}

/**
 * SetQuitHandler 设置安全退出回调
 */
export function SetQuitHandler(handler: any): $CancellablePromise<void> {
    return $Call.ByID(815395438, handler);
}

export function UpdateAppConfig(newConfig: appconf$0.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(3160634607, newConfig);
}

// Private type creation functions
const $$createType0 = appconf$0.AppConfig.createFrom;
