// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadService 管理所有下载任务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelDownload 取消指定任务
 */
export function CancelDownload(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3535354491, taskID);
}

export function CheckDownloadImportStates(requests: vo$0.DownloadImportStateRequest[]): $CancellablePromise<vo$0.DownloadImportState[]> {
    return $Call.ByID(2101105240, requests).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteDownloadTask 删除已结束的下载任务记录；未完成任务的残留文件一并清理
 */
export function DeleteDownloadTask(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3117689459, taskID);
}

/**
 * GetDownloadTasks 返回所有任务快照
 */
export function GetDownloadTasks(): $CancellablePromise<$models.DownloadTask[]> {
    return $Call.ByID(1454461175).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetPendingInstall 前端初始化完成后调用，获取并清除待安装请求
 */
export function GetPendingInstall(): $CancellablePromise<vo$0.InstallRequest | null> {
    return $Call.ByID(2901308177).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ImportDownloadTaskAsGame 将下载任务导入到游戏库（含元数据与可执行文件选择）
 */
export function ImportDownloadTaskAsGame(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2076088359, taskID);
}

/**
 * OpenDownloadTaskLocation 打开下载任务对应文件所在位置
 */
export function OpenDownloadTaskLocation(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(1159501479, taskID);
}

/**
 * PauseDownload 暂停下载任务（保留已下载部分，可恢复）
 */
export function PauseDownload(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3195254317, taskID);
}

/**
 * ResumeDownload 恢复已暂停任务
 */
export function ResumeDownload(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2439704110, taskID);
}

/**
 * RetryDownload 重新尝试一个失败的下载任务
 */
export function RetryDownload(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(1927391217, taskID);
}

/**
 * StartCoverImageDownloadTask creates a lightweight download-management task for batch cover caching.
 */
export function StartCoverImageDownloadTask(items: $models.CoverImageDownloadItem[]): $CancellablePromise<string> {
    return $Call.ByID(1554770426, items);
}

/**
 * StartDownload 开始一个下载任务，返回任务 ID
 */
export function StartDownload(req: vo$0.InstallRequest): $CancellablePromise<string> {
    return $Call.ByID(1166162743, req);
}

// Private type creation functions
const $$createType0 = vo$0.DownloadImportState.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.DownloadTask.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = vo$0.InstallRequest.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
