// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../common/enums/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function GetGameReview(gameID: string): $CancellablePromise<models$0.GameReview | null> {
    return $Call.ByID(1333778931, gameID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveGameReview(review: models$0.GameReview): $CancellablePromise<models$0.GameReview | null> {
    return $Call.ByID(3751796484, review).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SyncGameReview(gameID: string, providers: enums$0.SourceType[]): $CancellablePromise<vo$0.GameReviewSyncResult> {
    return $Call.ByID(4022764938, gameID, providers).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.GameReview.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = vo$0.GameReviewSyncResult.createFrom;
