// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../common/enums/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as processutils$0 from "../utils/processutils/models.js";

/**
 * AddGameFromWebMetadata 用于接收前端/导入流程中的完整刮削结果（含 tags）并一次性入库。
 */
export function AddGameFromWebMetadata(meta: vo$0.GameMetadataFromWebVO): $CancellablePromise<void> {
    return $Call.ByID(1984455319, meta);
}

/**
 * BatchUpdateStatus 批量更新多个游戏的游玩状态
 */
export function BatchUpdateStatus(ids: string[], status: string): $CancellablePromise<void> {
    return $Call.ByID(3920669870, ids, status);
}

export function DeleteGame(id: string): $CancellablePromise<void> {
    return $Call.ByID(3870112898, id);
}

export function DeleteGameMetadataSource(gameID: string, source: enums$0.SourceType): $CancellablePromise<void> {
    return $Call.ByID(1099719170, gameID, source);
}

export function DeleteGames(ids: string[]): $CancellablePromise<void> {
    return $Call.ByID(330755939, ids);
}

/**
 * DownloadCoverImage 下载远程封面图片并替换为本地托管路径。
 */
export function DownloadCoverImage(gameID: string, coverURL: string): $CancellablePromise<string> {
    return $Call.ByID(2159062323, gameID, coverURL);
}

/**
 * ExportLaunchShortcut exports a per-game .url shortcut that re-enters LunaBox via protocol.
 */
export function ExportLaunchShortcut(gameID: string): $CancellablePromise<string> {
    return $Call.ByID(1161923292, gameID);
}

export function FetchMetadata(req: vo$0.MetadataRequest): $CancellablePromise<models$0.Game> {
    return $Call.ByID(3526283416, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function FetchMetadataByName(name: string): $CancellablePromise<vo$0.GameMetadataFromWebVO[]> {
    return $Call.ByID(1725328630, name).then(($result: any) => {
        return $$createType2($result);
    });
}

export function FetchMetadataFromWeb(req: vo$0.MetadataRequest): $CancellablePromise<vo$0.GameMetadataFromWebVO> {
    return $Call.ByID(3772898958, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetGameByID(id: string): $CancellablePromise<models$0.Game> {
    return $Call.ByID(870918487, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetGameMetadataSources(gameID: string): $CancellablePromise<models$0.GameMetadataSource[]> {
    return $Call.ByID(1857994916, gameID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetGames(req: vo$0.GameListRequest): $CancellablePromise<vo$0.GameListResponse> {
    return $Call.ByID(3248875236, req).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetRunningProcesses 获取系统中正在运行的进程列表（过滤掉系统进程）
 */
export function GetRunningProcesses(): $CancellablePromise<processutils$0.ProcessInfo[]> {
    return $Call.ByID(3550673093).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * OpenLocalPath 打开指定的本地文件或目录（通过资源管理器）
 */
export function OpenLocalPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(4293749381, path);
}

export function RefreshAllGamesMetadata(): $CancellablePromise<vo$0.MetadataRefreshResult> {
    return $Call.ByID(3664175033).then(($result: any) => {
        return $$createType8($result);
    });
}

export function RefreshAllGamesMetadataWithFields(fields: enums$0.MetadataUpdateField[]): $CancellablePromise<vo$0.MetadataRefreshResult> {
    return $Call.ByID(1585598116, fields).then(($result: any) => {
        return $$createType8($result);
    });
}

export function RefreshGamesMetadata(gameIDs: string[]): $CancellablePromise<vo$0.MetadataRefreshResult> {
    return $Call.ByID(839615256, gameIDs).then(($result: any) => {
        return $$createType8($result);
    });
}

export function RefreshGamesMetadataWithFields(gameIDs: string[], fields: enums$0.MetadataUpdateField[]): $CancellablePromise<vo$0.MetadataRefreshResult> {
    return $Call.ByID(2614311709, gameIDs, fields).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ResolveExecutablePathForImport 解析导入时的可执行路径：
 * - 如果是可执行文件路径，直接返回
 * - 如果是目录，弹出文件选择器让用户手动选择可执行文件
 */
export function ResolveExecutablePathForImport(path: string): $CancellablePromise<string> {
    return $Call.ByID(3170117500, path);
}

/**
 * SaveCoverImageDataURL 保存前端剪贴板读取到的图片 data URL。
 */
export function SaveCoverImageDataURL(gameID: string, dataURL: string): $CancellablePromise<string> {
    return $Call.ByID(1501613755, gameID, dataURL);
}

/**
 * SelectCoverImage 选择封面图片并保存到 covers 目录
 */
export function SelectCoverImage(gameID: string): $CancellablePromise<string> {
    return $Call.ByID(3815698927, gameID);
}

/**
 * SelectCoverImageWithTempID 选择封面图片并使用临时ID保存（用于新增游戏时）
 */
export function SelectCoverImageWithTempID(): $CancellablePromise<string> {
    return $Call.ByID(2386568324);
}

export function SelectGameDirectory(currentPath: string): $CancellablePromise<string> {
    return $Call.ByID(2257419900, currentPath);
}

export function SelectGameExecutable(currentPath: string): $CancellablePromise<string> {
    return $Call.ByID(1819772025, currentPath);
}

/**
 * SelectSaveDirectory 选择存档目录
 */
export function SelectSaveDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1684294165);
}

/**
 * SelectSaveFile 选择存档文件
 */
export function SelectSaveFile(): $CancellablePromise<string> {
    return $Call.ByID(503879528);
}

export function SelectWineRunnerExecutable(currentPath: string): $CancellablePromise<string> {
    return $Call.ByID(2993135908, currentPath);
}

export function SetDefaultMetadataSource(gameID: string, source: enums$0.SourceType): $CancellablePromise<void> {
    return $Call.ByID(2476714738, gameID, source);
}

/**
 * StartRemoteCoverImageDownloadTask queues a download-management task for all games
 * whose current cover URL still points to a remote image.
 */
export function StartRemoteCoverImageDownloadTask(): $CancellablePromise<string> {
    return $Call.ByID(1394229022);
}

export function UpdateGame(game: models$0.Game): $CancellablePromise<void> {
    return $Call.ByID(340448976, game);
}

/**
 * UpdateGameFromRemote 从远程数据源更新游戏信息
 */
export function UpdateGameFromRemote(gameID: string): $CancellablePromise<void> {
    return $Call.ByID(768690102, gameID);
}

/**
 * UpdateGameFromRemoteBySource refreshes a game from one explicitly linked provider.
 */
export function UpdateGameFromRemoteBySource(gameID: string, source: enums$0.SourceType): $CancellablePromise<void> {
    return $Call.ByID(3791053690, gameID, source);
}

/**
 * UpdateGameFromRemoteWithFields 从远程数据源更新指定字段。
 */
export function UpdateGameFromRemoteWithFields(gameID: string, fields: enums$0.MetadataUpdateField[]): $CancellablePromise<void> {
    return $Call.ByID(1596043423, gameID, fields);
}

/**
 * UpdateGameProcessName 更新游戏的进程名
 * 当用户选择了实际的游戏进程时调用
 */
export function UpdateGameProcessName(gameID: string, processName: string): $CancellablePromise<void> {
    return $Call.ByID(2069268558, gameID, processName);
}

export function UpsertGameMetadataSource(gameID: string, source: enums$0.SourceType, sourceID: string): $CancellablePromise<void> {
    return $Call.ByID(81280994, gameID, source, sourceID);
}

// Private type creation functions
const $$createType0 = models$0.Game.createFrom;
const $$createType1 = vo$0.GameMetadataFromWebVO.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = models$0.GameMetadataSource.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = vo$0.GameListResponse.createFrom;
const $$createType6 = processutils$0.ProcessInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = vo$0.MetadataRefreshResult.createFrom;
