// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function CreateGameFilterPreset(req: vo$0.SaveGameFilterPresetRequest): $CancellablePromise<models$0.GameFilterPreset> {
    return $Call.ByID(2381435689, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DeleteGameFilterPreset(id: string): $CancellablePromise<void> {
    return $Call.ByID(2947034398, id);
}

export function ListGameFilterPresets(): $CancellablePromise<models$0.GameFilterPreset[]> {
    return $Call.ByID(1109001118).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateGameFilterPreset(id: string, req: vo$0.SaveGameFilterPresetRequest): $CancellablePromise<models$0.GameFilterPreset> {
    return $Call.ByID(2487581808, id, req).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.GameFilterPreset.createFrom;
const $$createType1 = $Create.Array($$createType0);
