// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../vo/models.js";

export function AddGame(game: models$0.Game): $CancellablePromise<void> {
    return $Call.ByID(1969549196, game);
}

export function DeleteGame(id: string): $CancellablePromise<void> {
    return $Call.ByID(3870112898, id);
}

export function FetchMetadata(req: vo$0.MetadataRequest): $CancellablePromise<models$0.Game> {
    return $Call.ByID(3526283416, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function FetchMetadataByName(name: string): $CancellablePromise<vo$0.GameMetadataFromWebVO[]> {
    return $Call.ByID(1725328630, name).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetGameByID(id: string): $CancellablePromise<models$0.Game> {
    return $Call.ByID(870918487, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetGames(): $CancellablePromise<models$0.Game[]> {
    return $Call.ByID(3248875236).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SelectCoverImage 选择封面图片并保存到 covers 目录
 */
export function SelectCoverImage(gameID: string): $CancellablePromise<string> {
    return $Call.ByID(3815698927, gameID);
}

/**
 * SelectCoverImageWithTempID 选择封面图片并使用临时ID保存（用于新增游戏时）
 */
export function SelectCoverImageWithTempID(): $CancellablePromise<string> {
    return $Call.ByID(2386568324);
}

export function SelectGameExecutable(): $CancellablePromise<string> {
    return $Call.ByID(1819772025);
}

/**
 * SelectSaveDirectory 选择存档目录
 */
export function SelectSaveDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1684294165);
}

export function UpdateGame(game: models$0.Game): $CancellablePromise<void> {
    return $Call.ByID(340448976, game);
}

/**
 * UpdateGameFromRemote 从远程数据源更新游戏信息
 */
export function UpdateGameFromRemote(gameID: string): $CancellablePromise<void> {
    return $Call.ByID(768690102, gameID);
}

// Private type creation functions
const $$createType0 = models$0.Game.createFrom;
const $$createType1 = vo$0.GameMetadataFromWebVO.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
