// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";

export function Disconnect(): $CancellablePromise<vo$0.HikarinagiAuthStatus> {
    return $Call.ByID(104554032).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetAuthStatus(): $CancellablePromise<vo$0.HikarinagiAuthStatus> {
    return $Call.ByID(3781905042).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetProfile(): $CancellablePromise<vo$0.HikarinagiProfile> {
    return $Call.ByID(2292117527).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StartAuth(): $CancellablePromise<vo$0.HikarinagiAuthStatus> {
    return $Call.ByID(110026484).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SyncAllGameStatuses(): $CancellablePromise<vo$0.RemoteStatusSyncProgress> {
    return $Call.ByID(2989962652).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = vo$0.HikarinagiAuthStatus.createFrom;
const $$createType1 = vo$0.HikarinagiProfile.createFrom;
const $$createType2 = vo$0.RemoteStatusSyncProgress.createFrom;
