// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../vo/models.js";

export function GetHomePageData(): $CancellablePromise<vo$0.HomePageData> {
    return $Call.ByID(2525952338).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetOrCreateCurrentUser(): $CancellablePromise<models$0.User> {
    return $Call.ByID(2185879951).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = vo$0.HomePageData.createFrom;
const $$createType1 = models$0.User.createFrom;
