// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../common/enums/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchImportGames 批量导入游戏
 */
export function BatchImportGames(candidates: vo$0.BatchImportCandidate[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(2272546492, candidates).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CheckImportMetadataDuplicates 批量检查元数据 source/id 是否已存在。
 */
export function CheckImportMetadataDuplicates(requests: vo$0.ImportMetadataDuplicateRequest[]): $CancellablePromise<vo$0.ImportMetadataDuplicateResult[]> {
    return $Call.ByID(3232680694, requests).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * FetchMetadataForCandidate 为单个候选项获取元数据（带限流）
 */
export function FetchMetadataForCandidate(searchName: string): $CancellablePromise<vo$0.BatchImportCandidate> {
    return $Call.ByID(2917695493, searchName).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * FetchMetadataForCandidateWithPreference fetches and filters metadata for bulk import.
 * A configured preferred source is authoritative. Without one, the search name is
 * used as the reference for every enabled source.
 */
export function FetchMetadataForCandidateWithPreference(searchName: string, preferredSource: enums$0.SourceType): $CancellablePromise<vo$0.BatchImportMetadataMatchResult> {
    return $Call.ByID(1340429536, searchName, preferredSource).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ImportFromPlaynite 从 Playnite 导出的 JSON 文件导入数据
 */
export function ImportFromPlaynite(jsonPath: string, skipNoPath: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(407725221, jsonPath, skipNoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromPlayniteWithOptions(jsonPath: string, skipNoPath: boolean, samePathAction: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(2716991313, jsonPath, skipNoPath, samePathAction).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromPlayniteWithSelection(jsonPath: string, skipNoPath: boolean, samePathAction: string, selections: vo$0.ImportSelection[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(3115797393, jsonPath, skipNoPath, samePathAction, selections).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromPotatoVN 从 PotatoVN 导出的 ZIP 文件导入数据
 */
export function ImportFromPotatoVN(zipPath: string, skipNoPath: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(2195766462, zipPath, skipNoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromPotatoVNWithOptions(zipPath: string, skipNoPath: boolean, samePathAction: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(3975548404, zipPath, skipNoPath, samePathAction).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromPotatoVNWithSelection(zipPath: string, skipNoPath: boolean, samePathAction: string, selections: vo$0.ImportSelection[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(1528923484, zipPath, skipNoPath, samePathAction, selections).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromReinaManager 从 ReinaManager SQLite 数据库备份导入数据。
 */
export function ImportFromReinaManager(dbPath: string, skipNoPath: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(726358553, dbPath, skipNoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromReinaManagerWithOptions(dbPath: string, skipNoPath: boolean, samePathAction: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(2434128349, dbPath, skipNoPath, samePathAction).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromReinaManagerWithSelection(dbPath: string, skipNoPath: boolean, samePathAction: string, selections: vo$0.ImportSelection[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(4135033037, dbPath, skipNoPath, samePathAction, selections).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromSteamLocal 从本机 Steam 库导入已安装游戏。
 */
export function ImportFromSteamLocal(skipNoPath: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(597689546, skipNoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromSteamLocalWithOptions(skipNoPath: boolean, samePathAction: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(885223224, skipNoPath, samePathAction).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromSteamLocalWithSelection(skipNoPath: boolean, samePathAction: string, selections: vo$0.ImportSelection[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(467187792, skipNoPath, samePathAction, selections).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromVnite 从 Vnite 导出的数据库目录导入数据
 */
export function ImportFromVnite(vniteDir: string, skipNoPath: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(4287218471, vniteDir, skipNoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromVniteWithOptions(vniteDir: string, skipNoPath: boolean, samePathAction: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(3991927723, vniteDir, skipNoPath, samePathAction).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromVniteWithSelection(vniteDir: string, skipNoPath: boolean, samePathAction: string, selections: vo$0.ImportSelection[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(4100496827, vniteDir, skipNoPath, samePathAction, selections).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromYukiHub 从 YukiHub 备份导入游戏与游玩记录。
 */
export function ImportFromYukiHub(backupPath: string, skipNoPath: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(3046190802, backupPath, skipNoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromYukiHubWithOptions(backupPath: string, skipNoPath: boolean, samePathAction: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(502280432, backupPath, skipNoPath, samePathAction).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromYukiHubWithSelection(backupPath: string, skipNoPath: boolean, samePathAction: string, selections: vo$0.ImportSelection[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(1236415592, backupPath, skipNoPath, samePathAction, selections).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PreviewImport 预览 PotatoVN 导入内容（不实际导入）
 */
export function PreviewImport(zipPath: string): $CancellablePromise<$models.PreviewGame[]> {
    return $Call.ByID(2403517769, zipPath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PreviewPlayniteImport 预览 Playnite 导入内容（不实际导入）
 */
export function PreviewPlayniteImport(jsonPath: string): $CancellablePromise<$models.PreviewGame[]> {
    return $Call.ByID(4107361765, jsonPath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PreviewReinaManagerImport 预览 ReinaManager 数据库备份中的游戏。
 */
export function PreviewReinaManagerImport(dbPath: string): $CancellablePromise<$models.PreviewGame[]> {
    return $Call.ByID(461304041, dbPath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PreviewSteamLocalImport 扫描本机已安装 Steam 游戏并预览导入内容。
 */
export function PreviewSteamLocalImport(): $CancellablePromise<$models.PreviewGame[]> {
    return $Call.ByID(1217506118).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PreviewVniteImport 预览 Vnite 导入内容（不实际导入）
 */
export function PreviewVniteImport(vniteDir: string): $CancellablePromise<$models.PreviewGame[]> {
    return $Call.ByID(3206604861, vniteDir).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PreviewYukiHubImport 预览 YukiHub 备份中的游戏。
 */
export function PreviewYukiHubImport(backupPath: string): $CancellablePromise<$models.PreviewGame[]> {
    return $Call.ByID(566310536, backupPath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ProcessDroppedPaths 处理拖拽导入的路径，支持文件夹和可执行文件
 * 返回候选游戏列表供前端展示和确认
 */
export function ProcessDroppedPaths(paths: string[]): $CancellablePromise<vo$0.BatchImportScanResult> {
    return $Call.ByID(2364795639, paths).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ProcessDroppedPathsWithOptions 处理拖拽导入的路径，并复用批量导入的扫描命名选项。
 */
export function ProcessDroppedPathsWithOptions(paths: string[], options: vo$0.BatchImportScanOptions): $CancellablePromise<vo$0.BatchImportScanResult> {
    return $Call.ByID(865702907, paths, options).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ScanLibraryDirectory 扫描游戏库目录，返回默认待导入候选项和路径阶段跳过项。
 */
export function ScanLibraryDirectory(libraryPath: string): $CancellablePromise<vo$0.BatchImportScanResult> {
    return $Call.ByID(3828536207, libraryPath).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ScanLibraryDirectoryWithOptions 按指定模式扫描游戏库目录。
 */
export function ScanLibraryDirectoryWithOptions(libraryPath: string, options: vo$0.BatchImportScanOptions): $CancellablePromise<vo$0.BatchImportScanResult> {
    return $Call.ByID(334794435, libraryPath, options).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SelectJSONFile 选择要导入的 JSON 文件
 */
export function SelectJSONFile(): $CancellablePromise<string> {
    return $Call.ByID(2819581164);
}

/**
 * SelectLibraryDirectory 选择游戏库目录
 */
export function SelectLibraryDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3578812674);
}

/**
 * SelectReinaManagerDatabase 选择 ReinaManager 导出的 SQLite 数据库备份。
 */
export function SelectReinaManagerDatabase(): $CancellablePromise<string> {
    return $Call.ByID(2679041269);
}

/**
 * SelectVniteDirectory 选择 Vnite 导出的数据库目录
 */
export function SelectVniteDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3736503863);
}

/**
 * SelectYukiHubBackup 选择 YukiHub 导出的备份文件。
 */
export function SelectYukiHubBackup(): $CancellablePromise<string> {
    return $Call.ByID(2200677895);
}

/**
 * SelectZipFile 选择要导入的 ZIP 文件
 */
export function SelectZipFile(): $CancellablePromise<string> {
    return $Call.ByID(2300022041);
}

// Private type creation functions
const $$createType0 = $models.ImportResult.createFrom;
const $$createType1 = vo$0.ImportMetadataDuplicateResult.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = vo$0.BatchImportCandidate.createFrom;
const $$createType4 = vo$0.BatchImportMetadataMatchResult.createFrom;
const $$createType5 = $models.PreviewGame.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = vo$0.BatchImportScanResult.createFrom;
