// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../vo/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchImportGames 批量导入游戏
 */
export function BatchImportGames(candidates: vo$0.BatchImportCandidate[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(2272546492, candidates).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * FetchMetadataForCandidate 为单个候选项获取元数据（带限流）
 */
export function FetchMetadataForCandidate(searchName: string): $CancellablePromise<vo$0.BatchImportCandidate> {
    return $Call.ByID(2917695493, searchName).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportFromPlaynite 从 Playnite 导出的 JSON 文件导入数据
 */
export function ImportFromPlaynite(jsonPath: string, skipNoPath: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(407725221, jsonPath, skipNoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromPotatoVN 从 PotatoVN 导出的 ZIP 文件导入数据
 */
export function ImportFromPotatoVN(zipPath: string, skipNoPath: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(2195766462, zipPath, skipNoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PreviewImport 预览导入内容（不实际导入）
 */
export function PreviewImport(zipPath: string): $CancellablePromise<$models.PreviewGame[]> {
    return $Call.ByID(2403517769, zipPath).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * PreviewPlayniteImport 预览 Playnite 导入内容（不实际导入）
 */
export function PreviewPlayniteImport(jsonPath: string): $CancellablePromise<$models.PreviewGame[]> {
    return $Call.ByID(4107361765, jsonPath).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ScanLibraryDirectory 扫描游戏库目录，返回候选游戏列表
 */
export function ScanLibraryDirectory(libraryPath: string): $CancellablePromise<vo$0.BatchImportCandidate[]> {
    return $Call.ByID(3828536207, libraryPath).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SelectJSONFile 选择要导入的 JSON 文件
 */
export function SelectJSONFile(): $CancellablePromise<string> {
    return $Call.ByID(2819581164);
}

/**
 * SelectLibraryDirectory 选择游戏库目录
 */
export function SelectLibraryDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3578812674);
}

/**
 * SelectZipFile 选择要导入的 ZIP 文件
 */
export function SelectZipFile(): $CancellablePromise<string> {
    return $Call.ByID(2300022041);
}

/**
 * SetGameService 设置 GameService（用于导入游戏）
 */
export function SetGameService(gameService: $models.GameService | null): $CancellablePromise<void> {
    return $Call.ByID(1033575993, gameService);
}

/**
 * SetTimerService 设置 TimerService（用于导入游玩记录）
 */
export function SetTimerService(timerService: $models.TimerService | null): $CancellablePromise<void> {
    return $Call.ByID(1344227120, timerService);
}

// Private type creation functions
const $$createType0 = $models.ImportResult.createFrom;
const $$createType1 = vo$0.BatchImportCandidate.createFrom;
const $$createType2 = $models.PreviewGame.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType1);
