// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BatchImportGamesToSteam(gameIDs: string[]): $CancellablePromise<$models.SteamBatchImportResult> {
    return $Call.ByID(1977994590, gameIDs).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetGameSteamCompatibility(gameID: string): $CancellablePromise<$models.SteamCompatibilityInfo> {
    return $Call.ByID(690691647, gameID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetGameSteamStatus(gameID: string): $CancellablePromise<$models.SteamLaunchStatus> {
    return $Call.ByID(2802483307, gameID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ImportGameToSteam(gameID: string): $CancellablePromise<$models.SteamImportResult> {
    return $Call.ByID(690205899, gameID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function OpenGameSteamProtonPrefix(gameID: string): $CancellablePromise<string> {
    return $Call.ByID(2267806707, gameID);
}

export function RestartSteamClient(): $CancellablePromise<void> {
    return $Call.ByID(4268546093);
}

export function SetGameSteamCompatibilityTool(gameID: string, toolName: string): $CancellablePromise<$models.SteamCompatibilityInfo> {
    return $Call.ByID(2860498925, gameID, toolName).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetGameSteamLaunchOptions(gameID: string, launchOptions: string): $CancellablePromise<$models.SteamLaunchStatus> {
    return $Call.ByID(2796489024, gameID, launchOptions).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SteamBatchImportResult.createFrom;
const $$createType1 = $models.SteamCompatibilityInfo.createFrom;
const $$createType2 = $models.SteamLaunchStatus.createFrom;
const $$createType3 = $models.SteamImportResult.createFrom;
