// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * ActiveTimeTracker 活跃时间追踪服务
 * 使用轮询方式检测窗口焦点状态，仅当游戏窗口处于前台时记录游玩时长
 */
export class ActiveTimeTracker {

    /** Creates a new ActiveTimeTracker instance. */
    constructor($$source: Partial<ActiveTimeTracker> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActiveTimeTracker instance from a string or object.
     */
    static createFrom($$source: any = {}): ActiveTimeTracker {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActiveTimeTracker($$parsedSource as Partial<ActiveTimeTracker>);
    }
}

export class BackupService {

    /** Creates a new BackupService instance. */
    constructor($$source: Partial<BackupService> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupService instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupService {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupService($$parsedSource as Partial<BackupService>);
    }
}

export class ConfigService {

    /** Creates a new ConfigService instance. */
    constructor($$source: Partial<ConfigService> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigService instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigService {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigService($$parsedSource as Partial<ConfigService>);
    }
}

export class GameService {

    /** Creates a new GameService instance. */
    constructor($$source: Partial<GameService> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameService instance from a string or object.
     */
    static createFrom($$source: any = {}): GameService {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameService($$parsedSource as Partial<GameService>);
    }
}

/**
 * ImportResult 导入结果
 */
export class ImportResult {
    /**
     * 成功导入数量
     */
    "success": number;

    /**
     * 跳过数量（已存在）
     */
    "skipped": number;

    /**
     * 失败数量
     */
    "failed": number;

    /**
     * 失败的游戏名称
     */
    "failed_names": string[];

    /**
     * 跳过的游戏名称
     */
    "skipped_names": string[];

    /**
     * 导入的游玩记录数量
     */
    "sessions_imported": number;

    /** Creates a new ImportResult instance. */
    constructor($$source: Partial<ImportResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("failed_names" in $$source)) {
            this["failed_names"] = [];
        }
        if (!("skipped_names" in $$source)) {
            this["skipped_names"] = [];
        }
        if (!("sessions_imported" in $$source)) {
            this["sessions_imported"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportResult {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("failed_names" in $$parsedSource) {
            $$parsedSource["failed_names"] = $$createField3_0($$parsedSource["failed_names"]);
        }
        if ("skipped_names" in $$parsedSource) {
            $$parsedSource["skipped_names"] = $$createField4_0($$parsedSource["skipped_names"]);
        }
        return new ImportResult($$parsedSource as Partial<ImportResult>);
    }
}

/**
 * PreviewGame 预览导入的游戏信息
 */
export class PreviewGame {
    "name": string;
    "developer": string;
    "source_type": string;
    "exists": boolean;
    "add_time": time$0.Time;

    /**
     * 用于 Playnite 导入，标记是否有路径
     */
    "has_path": boolean;

    /** Creates a new PreviewGame instance. */
    constructor($$source: Partial<PreviewGame> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("developer" in $$source)) {
            this["developer"] = "";
        }
        if (!("source_type" in $$source)) {
            this["source_type"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("add_time" in $$source)) {
            this["add_time"] = null;
        }
        if (!("has_path" in $$source)) {
            this["has_path"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewGame instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewGame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreviewGame($$parsedSource as Partial<PreviewGame>);
    }
}

export class TimerService {

    /** Creates a new TimerService instance. */
    constructor($$source: Partial<TimerService> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimerService instance from a string or object.
     */
    static createFrom($$source: any = {}): TimerService {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimerService($$parsedSource as Partial<TimerService>);
    }
}

/**
 * UpdateCheckResult 更新检查结果
 */
export class UpdateCheckResult {
    /**
     * 是否有更新
     */
    "has_update": boolean;

    /**
     * 当前版本
     */
    "current_ver": string;

    /**
     * 最新版本
     */
    "latest_ver": string;

    /**
     * 发布日期
     */
    "release_date": string;

    /**
     * 更新日志内容
     */
    "changelog": string[];

    /**
     * 下载链接
     */
    "downloads": { [_: string]: string };

    /** Creates a new UpdateCheckResult instance. */
    constructor($$source: Partial<UpdateCheckResult> = {}) {
        if (!("has_update" in $$source)) {
            this["has_update"] = false;
        }
        if (!("current_ver" in $$source)) {
            this["current_ver"] = "";
        }
        if (!("latest_ver" in $$source)) {
            this["latest_ver"] = "";
        }
        if (!("release_date" in $$source)) {
            this["release_date"] = "";
        }
        if (!("changelog" in $$source)) {
            this["changelog"] = [];
        }
        if (!("downloads" in $$source)) {
            this["downloads"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateCheckResult {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changelog" in $$parsedSource) {
            $$parsedSource["changelog"] = $$createField4_0($$parsedSource["changelog"]);
        }
        if ("downloads" in $$parsedSource) {
            $$parsedSource["downloads"] = $$createField5_0($$parsedSource["downloads"]);
        }
        return new UpdateCheckResult($$parsedSource as Partial<UpdateCheckResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
