// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";

export class CoverImageDownloadItem {
    "GameID": string;
    "GameName": string;
    "CoverURL": string;

    /** Creates a new CoverImageDownloadItem instance. */
    constructor($$source: Partial<CoverImageDownloadItem> = {}) {
        if (!("GameID" in $$source)) {
            this["GameID"] = "";
        }
        if (!("GameName" in $$source)) {
            this["GameName"] = "";
        }
        if (!("CoverURL" in $$source)) {
            this["CoverURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoverImageDownloadItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CoverImageDownloadItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CoverImageDownloadItem($$parsedSource as Partial<CoverImageDownloadItem>);
    }
}

/**
 * DownloadStatus 下载状态
 */
export enum DownloadStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DownloadStatusPending = "pending",
    DownloadStatusDownloading = "downloading",
    DownloadStatusExtracting = "extracting",
    DownloadStatusPaused = "paused",
    DownloadStatusDone = "done",
    DownloadStatusError = "error",
    DownloadStatusCancelled = "cancelled",
};

/**
 * DownloadTask 单个下载任务
 */
export class DownloadTask {
    "id": string;
    "request": vo$0.InstallRequest;
    "status": DownloadStatus;
    "created_at"?: string | null;

    /**
     * 0~100
     */
    "progress": number;

    /**
     * bytes downloaded
     */
    "downloaded": number;

    /**
     * bytes total (0 = unknown)
     */
    "total": number;
    "error"?: string;

    /**
     * 下载完成后的本地路径
     */
    "file_path"?: string;

    /** Creates a new DownloadTask instance. */
    constructor($$source: Partial<DownloadTask> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("request" in $$source)) {
            this["request"] = (new vo$0.InstallRequest());
        }
        if (!("status" in $$source)) {
            this["status"] = DownloadStatus.$zero;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadTask instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadTask {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField1_0($$parsedSource["request"]);
        }
        return new DownloadTask($$parsedSource as Partial<DownloadTask>);
    }
}

export class GameLibraryPathChangeItem {
    "record_type": string;
    "record_id": string;
    "record_name": string;
    "field": string;
    "old_path": string;
    "new_path": string;
    "target_exists": boolean;
    "steam_managed": boolean;

    /** Creates a new GameLibraryPathChangeItem instance. */
    constructor($$source: Partial<GameLibraryPathChangeItem> = {}) {
        if (!("record_type" in $$source)) {
            this["record_type"] = "";
        }
        if (!("record_id" in $$source)) {
            this["record_id"] = "";
        }
        if (!("record_name" in $$source)) {
            this["record_name"] = "";
        }
        if (!("field" in $$source)) {
            this["field"] = "";
        }
        if (!("old_path" in $$source)) {
            this["old_path"] = "";
        }
        if (!("new_path" in $$source)) {
            this["new_path"] = "";
        }
        if (!("target_exists" in $$source)) {
            this["target_exists"] = false;
        }
        if (!("steam_managed" in $$source)) {
            this["steam_managed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameLibraryPathChangeItem instance from a string or object.
     */
    static createFrom($$source: any = {}): GameLibraryPathChangeItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameLibraryPathChangeItem($$parsedSource as Partial<GameLibraryPathChangeItem>);
    }
}

export class GameLibraryPathChangePreview {
    "old_configured_path": string;
    "new_configured_path": string;
    "old_library_path": string;
    "new_library_path": string;
    "changes": GameLibraryPathChangeItem[];
    "affected_game_count": number;
    "affected_download_task_count": number;
    "missing_target_count": number;
    "steam_game_count": number;
    "blocking_download_task_count": number;

    /** Creates a new GameLibraryPathChangePreview instance. */
    constructor($$source: Partial<GameLibraryPathChangePreview> = {}) {
        if (!("old_configured_path" in $$source)) {
            this["old_configured_path"] = "";
        }
        if (!("new_configured_path" in $$source)) {
            this["new_configured_path"] = "";
        }
        if (!("old_library_path" in $$source)) {
            this["old_library_path"] = "";
        }
        if (!("new_library_path" in $$source)) {
            this["new_library_path"] = "";
        }
        if (!("changes" in $$source)) {
            this["changes"] = [];
        }
        if (!("affected_game_count" in $$source)) {
            this["affected_game_count"] = 0;
        }
        if (!("affected_download_task_count" in $$source)) {
            this["affected_download_task_count"] = 0;
        }
        if (!("missing_target_count" in $$source)) {
            this["missing_target_count"] = 0;
        }
        if (!("steam_game_count" in $$source)) {
            this["steam_game_count"] = 0;
        }
        if (!("blocking_download_task_count" in $$source)) {
            this["blocking_download_task_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameLibraryPathChangePreview instance from a string or object.
     */
    static createFrom($$source: any = {}): GameLibraryPathChangePreview {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField4_0($$parsedSource["changes"]);
        }
        return new GameLibraryPathChangePreview($$parsedSource as Partial<GameLibraryPathChangePreview>);
    }
}

export class GameLibraryPathChangeResult {
    "new_configured_path": string;
    "updated_game_count": number;
    "updated_download_task_count": number;

    /** Creates a new GameLibraryPathChangeResult instance. */
    constructor($$source: Partial<GameLibraryPathChangeResult> = {}) {
        if (!("new_configured_path" in $$source)) {
            this["new_configured_path"] = "";
        }
        if (!("updated_game_count" in $$source)) {
            this["updated_game_count"] = 0;
        }
        if (!("updated_download_task_count" in $$source)) {
            this["updated_download_task_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameLibraryPathChangeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GameLibraryPathChangeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameLibraryPathChangeResult($$parsedSource as Partial<GameLibraryPathChangeResult>);
    }
}

/**
 * ImportResult 导入结果
 */
export class ImportResult {
    /**
     * 成功导入数量
     */
    "success": number;

    /**
     * 跳过数量（已存在）
     */
    "skipped": number;

    /**
     * 失败数量
     */
    "failed": number;

    /**
     * 失败的游戏名称
     */
    "failed_names": string[];

    /**
     * 跳过的游戏名称
     */
    "skipped_names": string[];

    /**
     * 导入的游玩记录数量
     */
    "sessions_imported": number;

    /** Creates a new ImportResult instance. */
    constructor($$source: Partial<ImportResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("failed_names" in $$source)) {
            this["failed_names"] = [];
        }
        if (!("skipped_names" in $$source)) {
            this["skipped_names"] = [];
        }
        if (!("sessions_imported" in $$source)) {
            this["sessions_imported"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportResult {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("failed_names" in $$parsedSource) {
            $$parsedSource["failed_names"] = $$createField3_0($$parsedSource["failed_names"]);
        }
        if ("skipped_names" in $$parsedSource) {
            $$parsedSource["skipped_names"] = $$createField4_0($$parsedSource["skipped_names"]);
        }
        return new ImportResult($$parsedSource as Partial<ImportResult>);
    }
}

/**
 * PortableCLIStatus describes the lunacli.exe presence and PATH registration.
 */
export class PortableCLIStatus {
    "available": boolean;
    "cliPath": string;
    "cliDir": string;
    "installPath": string;
    "installDir": string;
    "registered": boolean;

    /** Creates a new PortableCLIStatus instance. */
    constructor($$source: Partial<PortableCLIStatus> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("cliPath" in $$source)) {
            this["cliPath"] = "";
        }
        if (!("cliDir" in $$source)) {
            this["cliDir"] = "";
        }
        if (!("installPath" in $$source)) {
            this["installPath"] = "";
        }
        if (!("installDir" in $$source)) {
            this["installDir"] = "";
        }
        if (!("registered" in $$source)) {
            this["registered"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortableCLIStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PortableCLIStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortableCLIStatus($$parsedSource as Partial<PortableCLIStatus>);
    }
}

/**
 * PortableProtocolStatus describes the current lunabox:// scheme binding.
 */
export class PortableProtocolStatus {
    "registered": boolean;
    "registeredPath": string;
    "currentPath": string;
    "upToDate": boolean;

    /** Creates a new PortableProtocolStatus instance. */
    constructor($$source: Partial<PortableProtocolStatus> = {}) {
        if (!("registered" in $$source)) {
            this["registered"] = false;
        }
        if (!("registeredPath" in $$source)) {
            this["registeredPath"] = "";
        }
        if (!("currentPath" in $$source)) {
            this["currentPath"] = "";
        }
        if (!("upToDate" in $$source)) {
            this["upToDate"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortableProtocolStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PortableProtocolStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortableProtocolStatus($$parsedSource as Partial<PortableProtocolStatus>);
    }
}

/**
 * PortableSetupStatus is the aggregate snapshot consumed by the settings UI.
 */
export class PortableSetupStatus {
    "buildMode": string;
    "isPortable": boolean;
    "platform": string;
    "executablePath": string;
    "protocol": PortableProtocolStatus;
    "cli": PortableCLIStatus;

    /** Creates a new PortableSetupStatus instance. */
    constructor($$source: Partial<PortableSetupStatus> = {}) {
        if (!("buildMode" in $$source)) {
            this["buildMode"] = "";
        }
        if (!("isPortable" in $$source)) {
            this["isPortable"] = false;
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("executablePath" in $$source)) {
            this["executablePath"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = (new PortableProtocolStatus());
        }
        if (!("cli" in $$source)) {
            this["cli"] = (new PortableCLIStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortableSetupStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PortableSetupStatus {
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("protocol" in $$parsedSource) {
            $$parsedSource["protocol"] = $$createField4_0($$parsedSource["protocol"]);
        }
        if ("cli" in $$parsedSource) {
            $$parsedSource["cli"] = $$createField5_0($$parsedSource["cli"]);
        }
        return new PortableSetupStatus($$parsedSource as Partial<PortableSetupStatus>);
    }
}

/**
 * PreviewGame 预览导入的游戏信息
 */
export class PreviewGame {
    "name": string;
    "developer": string;
    "source_type": string;
    "source_id": string;
    "path": string;
    "exists": boolean;
    "conflict_type": string;
    "existing_id": string;
    "existing_name": string;
    "add_time": string;
    "has_path": boolean;

    /** Creates a new PreviewGame instance. */
    constructor($$source: Partial<PreviewGame> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("developer" in $$source)) {
            this["developer"] = "";
        }
        if (!("source_type" in $$source)) {
            this["source_type"] = "";
        }
        if (!("source_id" in $$source)) {
            this["source_id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("conflict_type" in $$source)) {
            this["conflict_type"] = "";
        }
        if (!("existing_id" in $$source)) {
            this["existing_id"] = "";
        }
        if (!("existing_name" in $$source)) {
            this["existing_name"] = "";
        }
        if (!("add_time" in $$source)) {
            this["add_time"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("has_path" in $$source)) {
            this["has_path"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewGame instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewGame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreviewGame($$parsedSource as Partial<PreviewGame>);
    }
}

/**
 * StartupFailure contains the diagnostic message shown when LunaBox cannot
 * create its main window.
 */
export class StartupFailure {
    "message": string;

    /** Creates a new StartupFailure instance. */
    constructor($$source: Partial<StartupFailure> = {}) {
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartupFailure instance from a string or object.
     */
    static createFrom($$source: any = {}): StartupFailure {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartupFailure($$parsedSource as Partial<StartupFailure>);
    }
}

export class SteamBatchImportItemResult {
    "game_id": string;
    "status": SteamLaunchStatus;
    "imported": boolean;
    "error"?: string;

    /** Creates a new SteamBatchImportItemResult instance. */
    constructor($$source: Partial<SteamBatchImportItemResult> = {}) {
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = (new SteamLaunchStatus());
        }
        if (!("imported" in $$source)) {
            this["imported"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamBatchImportItemResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamBatchImportItemResult {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField1_0($$parsedSource["status"]);
        }
        return new SteamBatchImportItemResult($$parsedSource as Partial<SteamBatchImportItemResult>);
    }
}

export class SteamBatchImportResult {
    "items": SteamBatchImportItemResult[];
    "imported_count": number;
    "existing_count": number;
    "failed_count": number;
    "backup_path": string;

    /** Creates a new SteamBatchImportResult instance. */
    constructor($$source: Partial<SteamBatchImportResult> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("imported_count" in $$source)) {
            this["imported_count"] = 0;
        }
        if (!("existing_count" in $$source)) {
            this["existing_count"] = 0;
        }
        if (!("failed_count" in $$source)) {
            this["failed_count"] = 0;
        }
        if (!("backup_path" in $$source)) {
            this["backup_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamBatchImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamBatchImportResult {
        const $$createField0_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new SteamBatchImportResult($$parsedSource as Partial<SteamBatchImportResult>);
    }
}

export class SteamCompatibilityInfo {
    "supported": boolean;
    "steam_installed": boolean;
    "steam_root": string;
    "app_id": string;
    "proton_prefix": string;
    "current_tool": string;
    "default_tool": string;
    "tools": SteamCompatibilityTool[];

    /** Creates a new SteamCompatibilityInfo instance. */
    constructor($$source: Partial<SteamCompatibilityInfo> = {}) {
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("steam_installed" in $$source)) {
            this["steam_installed"] = false;
        }
        if (!("steam_root" in $$source)) {
            this["steam_root"] = "";
        }
        if (!("app_id" in $$source)) {
            this["app_id"] = "";
        }
        if (!("proton_prefix" in $$source)) {
            this["proton_prefix"] = "";
        }
        if (!("current_tool" in $$source)) {
            this["current_tool"] = "";
        }
        if (!("default_tool" in $$source)) {
            this["default_tool"] = "";
        }
        if (!("tools" in $$source)) {
            this["tools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamCompatibilityInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamCompatibilityInfo {
        const $$createField7_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField7_0($$parsedSource["tools"]);
        }
        return new SteamCompatibilityInfo($$parsedSource as Partial<SteamCompatibilityInfo>);
    }
}

export class SteamCompatibilityTool {
    "name": string;
    "display_name": string;
    "path": string;
    "built_in": boolean;

    /** Creates a new SteamCompatibilityTool instance. */
    constructor($$source: Partial<SteamCompatibilityTool> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("built_in" in $$source)) {
            this["built_in"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamCompatibilityTool instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamCompatibilityTool {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SteamCompatibilityTool($$parsedSource as Partial<SteamCompatibilityTool>);
    }
}

export class SteamImportResult {
    "status": SteamLaunchStatus;
    "imported": boolean;
    "backup_path": string;

    /** Creates a new SteamImportResult instance. */
    constructor($$source: Partial<SteamImportResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = (new SteamLaunchStatus());
        }
        if (!("imported" in $$source)) {
            this["imported"] = false;
        }
        if (!("backup_path" in $$source)) {
            this["backup_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamImportResult {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField0_0($$parsedSource["status"]);
        }
        return new SteamImportResult($$parsedSource as Partial<SteamImportResult>);
    }
}

export class SteamLaunchStatus {
    "state": string;
    "ready": boolean;
    "steam_installed": boolean;
    "steam_running": boolean;
    "launch_id": string;
    "launch_kind": string;
    "user_id": string;
    "proton_prefix": string;

    /** Creates a new SteamLaunchStatus instance. */
    constructor($$source: Partial<SteamLaunchStatus> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }
        if (!("steam_installed" in $$source)) {
            this["steam_installed"] = false;
        }
        if (!("steam_running" in $$source)) {
            this["steam_running"] = false;
        }
        if (!("launch_id" in $$source)) {
            this["launch_id"] = "";
        }
        if (!("launch_kind" in $$source)) {
            this["launch_kind"] = "";
        }
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("proton_prefix" in $$source)) {
            this["proton_prefix"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteamLaunchStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SteamLaunchStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SteamLaunchStatus($$parsedSource as Partial<SteamLaunchStatus>);
    }
}

export class UpdateApplyResult {
    "started": boolean;
    "fallback_used": boolean;
    "file_count": number;

    /** Creates a new UpdateApplyResult instance. */
    constructor($$source: Partial<UpdateApplyResult> = {}) {
        if (!("started" in $$source)) {
            this["started"] = false;
        }
        if (!("fallback_used" in $$source)) {
            this["fallback_used"] = false;
        }
        if (!("file_count" in $$source)) {
            this["file_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateApplyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateApplyResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateApplyResult($$parsedSource as Partial<UpdateApplyResult>);
    }
}

/**
 * UpdateCheckResult 更新检查结果
 */
export class UpdateCheckResult {
    /**
     * 是否有更新
     */
    "has_update": boolean;

    /**
     * 当前版本
     */
    "current_ver": string;

    /**
     * 最新版本
     */
    "latest_ver": string;

    /**
     * 发布日期
     */
    "release_date": string;

    /**
     * 更新日志内容
     */
    "changelog": string[];

    /**
     * 下载链接
     */
    "downloads": { [_ in string]?: string };

    /**
     * 应用内更新清单
     */
    "update_manifest_url": string;

    /** Creates a new UpdateCheckResult instance. */
    constructor($$source: Partial<UpdateCheckResult> = {}) {
        if (!("has_update" in $$source)) {
            this["has_update"] = false;
        }
        if (!("current_ver" in $$source)) {
            this["current_ver"] = "";
        }
        if (!("latest_ver" in $$source)) {
            this["latest_ver"] = "";
        }
        if (!("release_date" in $$source)) {
            this["release_date"] = "";
        }
        if (!("changelog" in $$source)) {
            this["changelog"] = [];
        }
        if (!("downloads" in $$source)) {
            this["downloads"] = {};
        }
        if (!("update_manifest_url" in $$source)) {
            this["update_manifest_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateCheckResult {
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changelog" in $$parsedSource) {
            $$parsedSource["changelog"] = $$createField4_0($$parsedSource["changelog"]);
        }
        if ("downloads" in $$parsedSource) {
            $$parsedSource["downloads"] = $$createField5_0($$parsedSource["downloads"]);
        }
        return new UpdateCheckResult($$parsedSource as Partial<UpdateCheckResult>);
    }
}

// Private type creation functions
const $$createType0 = vo$0.InstallRequest.createFrom;
const $$createType1 = GameLibraryPathChangeItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = PortableProtocolStatus.createFrom;
const $$createType5 = PortableCLIStatus.createFrom;
const $$createType6 = SteamLaunchStatus.createFrom;
const $$createType7 = SteamBatchImportItemResult.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = SteamCompatibilityTool.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Map($Create.Any, $Create.Any);
