// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * AddPlaySession 手动添加游玩记录
 * startTime: 开始时间
 * durationMinutes: 游玩时长（分钟）
 */
export function AddPlaySession(gameID: string, startTime: string, durationMinutes: number): $CancellablePromise<models$0.PlaySession> {
    return $Call.ByID(2534678266, gameID, startTime, durationMinutes).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BatchAddPlaySessions 批量添加游玩记录（用于导入）
 */
export function BatchAddPlaySessions(sessions: models$0.PlaySession[]): $CancellablePromise<void> {
    return $Call.ByID(2440460293, sessions);
}

/**
 * CleanupUnfinishedSessions 清理所有未完成的会话（程序启动或关闭时调用）。
 * 新式运行中会话使用 end_time IS NULL 标记，并以最后一次心跳保存的
 * duration/updated_at 恢复，避免把断电后的时间误算为游玩时间。
 * 同时兼容旧版本使用 duration == 0 且 end_time == start_time 的待完成记录。
 */
export function CleanupUnfinishedSessions(): $CancellablePromise<void> {
    return $Call.ByID(3276085847);
}

/**
 * CreatePendingSession 创建待完成的游戏会话（用于开始游戏时）
 * 返回创建的会话ID
 */
export function CreatePendingSession(gameID: string, startTime: string): $CancellablePromise<string> {
    return $Call.ByID(2270142728, gameID, startTime);
}

/**
 * DeletePlaySession 删除指定的游玩记录
 */
export function DeletePlaySession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2536031992, sessionID);
}

/**
 * GetPlaySessions 获取指定游戏的所有游玩记录
 */
export function GetPlaySessions(gameID: string): $CancellablePromise<models$0.PlaySession[]> {
    return $Call.ByID(444659908, gameID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdatePlaySession 更新游玩记录
 */
export function UpdatePlaySession(session: models$0.PlaySession): $CancellablePromise<void> {
    return $Call.ByID(1667179530, session);
}

// Private type creation functions
const $$createType0 = models$0.PlaySession.createFrom;
const $$createType1 = $Create.Array($$createType0);
