// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddPlaySession 手动添加游玩记录
 * startTime: 开始时间
 * durationMinutes: 游玩时长（分钟）
 */
export function AddPlaySession(gameID: string, startTime: time$0.Time, durationMinutes: number): $CancellablePromise<models$0.PlaySession> {
    return $Call.ByID(696823687, gameID, startTime, durationMinutes).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BatchAddPlaySessions 批量添加游玩记录（用于导入）
 */
export function BatchAddPlaySessions(sessions: models$0.PlaySession[]): $CancellablePromise<void> {
    return $Call.ByID(1370086404, sessions);
}

/**
 * DeletePlaySession 删除指定的游玩记录
 */
export function DeletePlaySession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(805142935, sessionID);
}

/**
 * GetPlaySessions 获取指定游戏的所有游玩记录
 */
export function GetPlaySessions(gameID: string): $CancellablePromise<models$0.PlaySession[]> {
    return $Call.ByID(3236133287, gameID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetActiveTimeTracker(activeTimeTracker: $models.ActiveTimeTracker | null): $CancellablePromise<void> {
    return $Call.ByID(980184649, activeTimeTracker);
}

/**
 * SetBackupService 设置备份服务（用于自动备份）
 */
export function SetBackupService(backupService: $models.BackupService | null): $CancellablePromise<void> {
    return $Call.ByID(2118763217, backupService);
}

/**
 * StartGameWithTracking 启动游戏并自动追踪游玩时长
 * 当游戏进程退出时，自动保存游玩记录到数据库
 */
export function StartGameWithTracking(gameID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2042725587, gameID);
}

/**
 * UpdatePlaySession 更新游玩记录
 */
export function UpdatePlaySession(session: models$0.PlaySession): $CancellablePromise<void> {
    return $Call.ByID(2392298533, session);
}

// Private type creation functions
const $$createType0 = models$0.PlaySession.createFrom;
const $$createType1 = $Create.Array($$createType0);
