// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService 更新服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates 手动检查更新（忽略跳过版本设置，总是检查最新版本）
 */
export function CheckForUpdates(): $CancellablePromise<$models.UpdateCheckResult | null> {
    return $Call.ByID(1711338931).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CheckForUpdatesOnStartup 启动时自动检查更新
 */
export function CheckForUpdatesOnStartup(): $CancellablePromise<$models.UpdateCheckResult | null> {
    return $Call.ByID(2742727795).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OpenDownloadURL 打开下载页面（已废弃，请在前端使用 runtime.BrowserOpenURL）
 */
export function OpenDownloadURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3576158613, url);
}

export function SetConfigService(service: $models.ConfigService | null): $CancellablePromise<void> {
    return $Call.ByID(2166521809, service);
}

/**
 * SkipVersion 跳过指定版本的更新
 */
export function SkipVersion(ver: string): $CancellablePromise<void> {
    return $Call.ByID(2435461893, ver);
}

// Private type creation functions
const $$createType0 = $models.UpdateCheckResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
