// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService 更新服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates 手动检查更新（忽略跳过版本设置，总是检查最新版本）
 */
export function CheckForUpdates(): $CancellablePromise<$models.UpdateCheckResult | null> {
    return $Call.ByID(1711338931).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CheckForUpdatesOnStartup 启动时自动检查更新
 */
export function CheckForUpdatesOnStartup(): $CancellablePromise<$models.UpdateCheckResult | null> {
    return $Call.ByID(2742727795).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DownloadAndApplyUpdate downloads verified update artifacts with LunaBox's
 * existing downloader, asks the standalone updater to prepare them, then starts
 * the updater in commit mode and enters the normal LunaBox shutdown flow.
 */
export function DownloadAndApplyUpdate(manifestURL: string): $CancellablePromise<$models.UpdateApplyResult | null> {
    return $Call.ByID(1901531138, manifestURL).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * OpenDownloadURL 打开下载页面（已废弃，请在前端使用 @wailsio/runtime 的 Browser.OpenURL）。
 */
export function OpenDownloadURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3576158613, url);
}

/**
 * SkipVersion 跳过指定版本的更新
 */
export function SkipVersion(ver: string): $CancellablePromise<void> {
    return $Call.ByID(2435461893, ver);
}

// Private type creation functions
const $$createType0 = $models.UpdateCheckResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.UpdateApplyResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
