// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetBuildMode 返回构建模式
 */
export function GetBuildMode(): $CancellablePromise<string> {
    return $Call.ByID(2173952530);
}

/**
 * GetBuildTime 返回构建时间
 */
export function GetBuildTime(): $CancellablePromise<string> {
    return $Call.ByID(4066483684);
}

/**
 * GetFullVersion 返回完整版本信息
 */
export function GetFullVersion(): $CancellablePromise<string> {
    return $Call.ByID(1762605110);
}

/**
 * GetVersion 返回版本号
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(2155983121);
}

/**
 * GetVersionInfo 返回版本信息对象
 */
export function GetVersionInfo(): $CancellablePromise<{ [_: string]: string }> {
    return $Call.ByID(1795860873).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
