// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * TagItem 表示从数据源拉取的单个 tag
 */
export class TagItem {
    "Name": string;

    /**
     * 'bangumi' | 'vndb' | 'ymgal' | 'steam' | 'hikarinagi'
     */
    "Source": string;

    /**
     * 归一化权重
     */
    "Weight": number;
    "IsSpoiler": boolean;

    /** Creates a new TagItem instance. */
    constructor($$source: Partial<TagItem> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }
        if (!("Weight" in $$source)) {
            this["Weight"] = 0;
        }
        if (!("IsSpoiler" in $$source)) {
            this["IsSpoiler"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TagItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TagItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TagItem($$parsedSource as Partial<TagItem>);
    }
}
