// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../enums/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as metadata$0 from "../../utils/metadata/models.js";

export class AISummaryRequest {
    /**
     * week, month, year
     */
    "dimension": string;

    /**
     * 覆盖全局防剧透等级：none | mild | full
     */
    "spoiler_level"?: string;

    /** Creates a new AISummaryRequest instance. */
    constructor($$source: Partial<AISummaryRequest> = {}) {
        if (!("dimension" in $$source)) {
            this["dimension"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISummaryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AISummaryRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AISummaryRequest($$parsedSource as Partial<AISummaryRequest>);
    }
}

/**
 * AISummaryResponse AI总结响应
 */
export class AISummaryResponse {
    "summary": string;
    "dimension": string;

    /**
     * 是否使用了 WebSearch 增强
     */
    "web_search_used": boolean;

    /** Creates a new AISummaryResponse instance. */
    constructor($$source: Partial<AISummaryResponse> = {}) {
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("dimension" in $$source)) {
            this["dimension"] = "";
        }
        if (!("web_search_used" in $$source)) {
            this["web_search_used"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISummaryResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): AISummaryResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AISummaryResponse($$parsedSource as Partial<AISummaryResponse>);
    }
}

export class BangumiAuthStatus {
    "authorized": boolean;
    "needs_reauthorization": boolean;
    "legacy_token": boolean;
    "user_id": string;
    "username": string;
    "avatar_url": string;
    "access_token_expires_at": string;
    "last_error": string;

    /** Creates a new BangumiAuthStatus instance. */
    constructor($$source: Partial<BangumiAuthStatus> = {}) {
        if (!("authorized" in $$source)) {
            this["authorized"] = false;
        }
        if (!("needs_reauthorization" in $$source)) {
            this["needs_reauthorization"] = false;
        }
        if (!("legacy_token" in $$source)) {
            this["legacy_token"] = false;
        }
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("avatar_url" in $$source)) {
            this["avatar_url"] = "";
        }
        if (!("access_token_expires_at" in $$source)) {
            this["access_token_expires_at"] = "";
        }
        if (!("last_error" in $$source)) {
            this["last_error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BangumiAuthStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): BangumiAuthStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BangumiAuthStatus($$parsedSource as Partial<BangumiAuthStatus>);
    }
}

export class BangumiProfile {
    "user_id": string;
    "username": string;
    "nickname": string;
    "avatar_url": string;
    "avatar_large": string;
    "avatar_medium": string;
    "avatar_small": string;

    /** Creates a new BangumiProfile instance. */
    constructor($$source: Partial<BangumiProfile> = {}) {
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("nickname" in $$source)) {
            this["nickname"] = "";
        }
        if (!("avatar_url" in $$source)) {
            this["avatar_url"] = "";
        }
        if (!("avatar_large" in $$source)) {
            this["avatar_large"] = "";
        }
        if (!("avatar_medium" in $$source)) {
            this["avatar_medium"] = "";
        }
        if (!("avatar_small" in $$source)) {
            this["avatar_small"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BangumiProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): BangumiProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BangumiProfile($$parsedSource as Partial<BangumiProfile>);
    }
}

/**
 * BatchImportCandidate 批量导入候选项
 */
export class BatchImportCandidate {
    /**
     * 文件夹路径
     */
    "folder_path": string;

    /**
     * 游戏根目录（可执行文件可能位于更深层级）
     */
    "game_directory": string;

    /**
     * 文件夹名
     */
    "folder_name": string;

    /**
     * 检测到的可执行文件列表
     */
    "executables": string[];

    /**
     * 选中的可执行文件
     */
    "selected_exe": string;

    /**
     * 用于搜索的名称（用户可编辑）
     */
    "search_name": string;

    /**
     * 本地扫描已知来源
     */
    "source_type"?: enums$0.SourceType;

    /**
     * 本地扫描已知来源 ID
     */
    "source_id"?: string;

    /**
     * 本地安装大小（bytes）
     */
    "size_on_disk"?: number;

    /**
     * 是否选中导入
     */
    "is_selected": boolean;

    /**
     * 匹配到的游戏信息
     */
    "matched_game"?: models$0.Game | null;

    /**
     * 匹配到的标签
     */
    "matched_tags"?: metadata$0.TagItem[];

    /**
     * 匹配来源
     */
    "match_source"?: enums$0.SourceType;

    /**
     * 匹配状态: pending, matched, not_found, error
     */
    "match_status": string;

    /**
     * 导入状态: new, exists_path, exists_source, exists_name_path, possible_duplicate
     */
    "import_status": string;

    /**
     * 跳过或疑似重复原因
     */
    "skip_reason"?: string;

    /**
     * 命中的已有游戏 ID
     */
    "existing_id"?: string;

    /**
     * 命中的已有游戏名称
     */
    "existing_name"?: string;

    /** Creates a new BatchImportCandidate instance. */
    constructor($$source: Partial<BatchImportCandidate> = {}) {
        if (!("folder_path" in $$source)) {
            this["folder_path"] = "";
        }
        if (!("game_directory" in $$source)) {
            this["game_directory"] = "";
        }
        if (!("folder_name" in $$source)) {
            this["folder_name"] = "";
        }
        if (!("executables" in $$source)) {
            this["executables"] = [];
        }
        if (!("selected_exe" in $$source)) {
            this["selected_exe"] = "";
        }
        if (!("search_name" in $$source)) {
            this["search_name"] = "";
        }
        if (!("is_selected" in $$source)) {
            this["is_selected"] = false;
        }
        if (!("match_status" in $$source)) {
            this["match_status"] = "";
        }
        if (!("import_status" in $$source)) {
            this["import_status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchImportCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchImportCandidate {
        const $$createField3_0 = $$createType0;
        const $$createField10_0 = $$createType2;
        const $$createField11_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("executables" in $$parsedSource) {
            $$parsedSource["executables"] = $$createField3_0($$parsedSource["executables"]);
        }
        if ("matched_game" in $$parsedSource) {
            $$parsedSource["matched_game"] = $$createField10_0($$parsedSource["matched_game"]);
        }
        if ("matched_tags" in $$parsedSource) {
            $$parsedSource["matched_tags"] = $$createField11_0($$parsedSource["matched_tags"]);
        }
        return new BatchImportCandidate($$parsedSource as Partial<BatchImportCandidate>);
    }
}

export class BatchImportMetadataMatchResult {
    "search_name": string;
    "preferred_source": enums$0.SourceType;
    "preferred_matched": boolean;
    "preferred_no_result": boolean;
    "preferred_rate_limited": boolean;
    "preferred_error"?: string;
    "matches": GameMetadataFromWebVO[];
    "source_errors"?: BatchImportMetadataSourceError[];

    /** Creates a new BatchImportMetadataMatchResult instance. */
    constructor($$source: Partial<BatchImportMetadataMatchResult> = {}) {
        if (!("search_name" in $$source)) {
            this["search_name"] = "";
        }
        if (!("preferred_source" in $$source)) {
            this["preferred_source"] = enums$0.SourceType.$zero;
        }
        if (!("preferred_matched" in $$source)) {
            this["preferred_matched"] = false;
        }
        if (!("preferred_no_result" in $$source)) {
            this["preferred_no_result"] = false;
        }
        if (!("preferred_rate_limited" in $$source)) {
            this["preferred_rate_limited"] = false;
        }
        if (!("matches" in $$source)) {
            this["matches"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchImportMetadataMatchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchImportMetadataMatchResult {
        const $$createField6_0 = $$createType6;
        const $$createField7_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField6_0($$parsedSource["matches"]);
        }
        if ("source_errors" in $$parsedSource) {
            $$parsedSource["source_errors"] = $$createField7_0($$parsedSource["source_errors"]);
        }
        return new BatchImportMetadataMatchResult($$parsedSource as Partial<BatchImportMetadataMatchResult>);
    }
}

export class BatchImportMetadataSourceError {
    "source": enums$0.SourceType;
    "error": string;
    "rate_limited": boolean;

    /** Creates a new BatchImportMetadataSourceError instance. */
    constructor($$source: Partial<BatchImportMetadataSourceError> = {}) {
        if (!("source" in $$source)) {
            this["source"] = enums$0.SourceType.$zero;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("rate_limited" in $$source)) {
            this["rate_limited"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchImportMetadataSourceError instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchImportMetadataSourceError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatchImportMetadataSourceError($$parsedSource as Partial<BatchImportMetadataSourceError>);
    }
}

/**
 * BatchImportScanOptions 批量导入扫盘选项。
 */
export class BatchImportScanOptions {
    /**
     * scan, hierarchy
     */
    "scan_mode": string;

    /**
     * parent, depth
     */
    "scan_name_mode": string;

    /**
     * scan 模式下用于取游戏名的目录层级，0 表示游戏库子一级
     */
    "name_depth": number;

    /**
     * hierarchy 模式下作为游戏目录的目录层级，0 表示游戏库子一级
     */
    "hierarchy_depth": number;

    /** Creates a new BatchImportScanOptions instance. */
    constructor($$source: Partial<BatchImportScanOptions> = {}) {
        if (!("scan_mode" in $$source)) {
            this["scan_mode"] = "";
        }
        if (!("scan_name_mode" in $$source)) {
            this["scan_name_mode"] = "";
        }
        if (!("name_depth" in $$source)) {
            this["name_depth"] = 0;
        }
        if (!("hierarchy_depth" in $$source)) {
            this["hierarchy_depth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchImportScanOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchImportScanOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatchImportScanOptions($$parsedSource as Partial<BatchImportScanOptions>);
    }
}

/**
 * BatchImportScanResult 批量导入扫描结果。
 * Candidates 是默认进入扫描预览和元数据匹配队列的新增候选项；
 * SkippedCandidates 是路径阶段已裁剪的候选项，可用于折叠明细。
 */
export class BatchImportScanResult {
    "candidates": BatchImportCandidate[];
    "skipped_candidates": BatchImportCandidate[];
    "total_detected": number;
    "skipped": number;

    /** Creates a new BatchImportScanResult instance. */
    constructor($$source: Partial<BatchImportScanResult> = {}) {
        if (!("candidates" in $$source)) {
            this["candidates"] = [];
        }
        if (!("skipped_candidates" in $$source)) {
            this["skipped_candidates"] = [];
        }
        if (!("total_detected" in $$source)) {
            this["total_detected"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchImportScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchImportScanResult {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("candidates" in $$parsedSource) {
            $$parsedSource["candidates"] = $$createField0_0($$parsedSource["candidates"]);
        }
        if ("skipped_candidates" in $$parsedSource) {
            $$parsedSource["skipped_candidates"] = $$createField1_0($$parsedSource["skipped_candidates"]);
        }
        return new BatchImportScanResult($$parsedSource as Partial<BatchImportScanResult>);
    }
}

export class CategoryGameCandidateRequest {
    "category_id": string;
    "limit": number;
    "offset": number;
    "search_query": string;

    /** Creates a new CategoryGameCandidateRequest instance. */
    constructor($$source: Partial<CategoryGameCandidateRequest> = {}) {
        if (!("category_id" in $$source)) {
            this["category_id"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("search_query" in $$source)) {
            this["search_query"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CategoryGameCandidateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CategoryGameCandidateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CategoryGameCandidateRequest($$parsedSource as Partial<CategoryGameCandidateRequest>);
    }
}

export class CategoryGameListRequest {
    "category_id": string;
    "limit": number;
    "offset": number;
    "search_query": string;
    "status"?: enums$0.GameStatus | null;
    "exclude_status"?: boolean;
    "tags": string[];
    "exclude_tags"?: boolean;
    "sort_by": enums$0.GameListSortBy;
    "sort_order": enums$0.SortOrder;

    /** Creates a new CategoryGameListRequest instance. */
    constructor($$source: Partial<CategoryGameListRequest> = {}) {
        if (!("category_id" in $$source)) {
            this["category_id"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("search_query" in $$source)) {
            this["search_query"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("sort_by" in $$source)) {
            this["sort_by"] = enums$0.GameListSortBy.$zero;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = enums$0.SortOrder.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CategoryGameListRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CategoryGameListRequest {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        return new CategoryGameListRequest($$parsedSource as Partial<CategoryGameListRequest>);
    }
}

export class CategoryVO {
    "id": string;
    "name": string;
    "emoji": string;
    "is_system": boolean;
    "created_at": string;
    "updated_at": string;
    "game_count": number;

    /** Creates a new CategoryVO instance. */
    constructor($$source: Partial<CategoryVO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("emoji" in $$source)) {
            this["emoji"] = "";
        }
        if (!("is_system" in $$source)) {
            this["is_system"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("game_count" in $$source)) {
            this["game_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CategoryVO instance from a string or object.
     */
    static createFrom($$source: any = {}): CategoryVO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CategoryVO($$parsedSource as Partial<CategoryVO>);
    }
}

/**
 * CloudBackupItem 云端备份项
 */
export class CloudBackupItem {
    /**
     * S3 对象 key
     */
    "key": string;

    /**
     * 显示名称
     */
    "name": string;

    /**
     * 文件大小
     */
    "size": number;

    /**
     * 创建时间
     */
    "created_at": string;

    /** Creates a new CloudBackupItem instance. */
    constructor($$source: Partial<CloudBackupItem> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloudBackupItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CloudBackupItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloudBackupItem($$parsedSource as Partial<CloudBackupItem>);
    }
}

/**
 * CloudBackupStatus 云备份状态
 */
export class CloudBackupStatus {
    /**
     * 是否启用
     */
    "enabled": boolean;

    /**
     * 是否已配置
     */
    "configured": boolean;

    /**
     * 用户标识
     */
    "user_id": string;

    /**
     * 云备份提供商: s3, onedrive
     */
    "provider": string;

    /** Creates a new CloudBackupStatus instance. */
    constructor($$source: Partial<CloudBackupStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("configured" in $$source)) {
            this["configured"] = false;
        }
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloudBackupStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): CloudBackupStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloudBackupStatus($$parsedSource as Partial<CloudBackupStatus>);
    }
}

/**
 * CloudSyncStatus 云同步状态
 */
export class CloudSyncStatus {
    "enabled": boolean;
    "configured": boolean;
    "syncing": boolean;
    "last_sync_time": string;
    "last_sync_status": string;
    "last_sync_error": string;

    /** Creates a new CloudSyncStatus instance. */
    constructor($$source: Partial<CloudSyncStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("configured" in $$source)) {
            this["configured"] = false;
        }
        if (!("syncing" in $$source)) {
            this["syncing"] = false;
        }
        if (!("last_sync_time" in $$source)) {
            this["last_sync_time"] = "";
        }
        if (!("last_sync_status" in $$source)) {
            this["last_sync_status"] = "";
        }
        if (!("last_sync_error" in $$source)) {
            this["last_sync_error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloudSyncStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): CloudSyncStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloudSyncStatus($$parsedSource as Partial<CloudSyncStatus>);
    }
}

/**
 * DBBackupInfo 数据库备份信息
 */
export class DBBackupInfo {
    /**
     * 备份文件路径
     */
    "path": string;

    /**
     * 显示名称
     */
    "name": string;

    /**
     * 文件大小
     */
    "size": number;

    /**
     * 创建时间
     */
    "created_at": string;

    /** Creates a new DBBackupInfo instance. */
    constructor($$source: Partial<DBBackupInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBBackupInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DBBackupInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DBBackupInfo($$parsedSource as Partial<DBBackupInfo>);
    }
}

/**
 * DBBackupStatus 数据库备份状态
 */
export class DBBackupStatus {
    /**
     * 上次备份时间
     */
    "last_backup_time": string;

    /**
     * 备份列表
     */
    "backups": DBBackupInfo[];

    /** Creates a new DBBackupStatus instance. */
    constructor($$source: Partial<DBBackupStatus> = {}) {
        if (!("last_backup_time" in $$source)) {
            this["last_backup_time"] = "";
        }
        if (!("backups" in $$source)) {
            this["backups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBBackupStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DBBackupStatus {
        const $$createField1_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("backups" in $$parsedSource) {
            $$parsedSource["backups"] = $$createField1_0($$parsedSource["backups"]);
        }
        return new DBBackupStatus($$parsedSource as Partial<DBBackupStatus>);
    }
}

export class DailyPlayTime {
    /**
     * YYYY-MM-DD
     */
    "date": string;

    /**
     * seconds
     */
    "duration": number;

    /** Creates a new DailyPlayTime instance. */
    constructor($$source: Partial<DailyPlayTime> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyPlayTime instance from a string or object.
     */
    static createFrom($$source: any = {}): DailyPlayTime {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DailyPlayTime($$parsedSource as Partial<DailyPlayTime>);
    }
}

export class DownloadImportState {
    "task_id": string;
    "imported": boolean;

    /** Creates a new DownloadImportState instance. */
    constructor($$source: Partial<DownloadImportState> = {}) {
        if (!("task_id" in $$source)) {
            this["task_id"] = "";
        }
        if (!("imported" in $$source)) {
            this["imported"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadImportState instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadImportState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadImportState($$parsedSource as Partial<DownloadImportState>);
    }
}

export class DownloadImportStateRequest {
    "task_id": string;
    "file_path": string;
    "meta_source": string;
    "meta_id": string;

    /** Creates a new DownloadImportStateRequest instance. */
    constructor($$source: Partial<DownloadImportStateRequest> = {}) {
        if (!("task_id" in $$source)) {
            this["task_id"] = "";
        }
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("meta_source" in $$source)) {
            this["meta_source"] = "";
        }
        if (!("meta_id" in $$source)) {
            this["meta_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadImportStateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadImportStateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadImportStateRequest($$parsedSource as Partial<DownloadImportStateRequest>);
    }
}

export class GameDetailStats {
    /**
     * week, month, all
     */
    "dimension": string;

    /**
     * YYYY-MM-DD
     */
    "start_date": string;

    /**
     * YYYY-MM-DD
     */
    "end_date": string;
    "total_play_count": number;
    "total_play_time": number;
    "today_play_time": number;
    "recent_play_history": DailyPlayTime[];

    /** Creates a new GameDetailStats instance. */
    constructor($$source: Partial<GameDetailStats> = {}) {
        if (!("dimension" in $$source)) {
            this["dimension"] = "";
        }
        if (!("start_date" in $$source)) {
            this["start_date"] = "";
        }
        if (!("end_date" in $$source)) {
            this["end_date"] = "";
        }
        if (!("total_play_count" in $$source)) {
            this["total_play_count"] = 0;
        }
        if (!("total_play_time" in $$source)) {
            this["total_play_time"] = 0;
        }
        if (!("today_play_time" in $$source)) {
            this["today_play_time"] = 0;
        }
        if (!("recent_play_history" in $$source)) {
            this["recent_play_history"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameDetailStats instance from a string or object.
     */
    static createFrom($$source: any = {}): GameDetailStats {
        const $$createField6_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("recent_play_history" in $$parsedSource) {
            $$parsedSource["recent_play_history"] = $$createField6_0($$parsedSource["recent_play_history"]);
        }
        return new GameDetailStats($$parsedSource as Partial<GameDetailStats>);
    }
}

export class GameListRequest {
    "limit": number;
    "offset": number;
    "search_query": string;
    "status"?: enums$0.GameStatus | null;
    "exclude_status"?: boolean;
    "tags": string[];
    "exclude_tags"?: boolean;
    "sort_by": enums$0.GameListSortBy;
    "sort_order": enums$0.SortOrder;

    /** Creates a new GameListRequest instance. */
    constructor($$source: Partial<GameListRequest> = {}) {
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("search_query" in $$source)) {
            this["search_query"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("sort_by" in $$source)) {
            this["sort_by"] = enums$0.GameListSortBy.$zero;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = enums$0.SortOrder.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameListRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GameListRequest {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        return new GameListRequest($$parsedSource as Partial<GameListRequest>);
    }
}

export class GameListResponse {
    "games": models$0.Game[];
    "limit": number;
    "offset": number;
    "total": number;
    "has_more": boolean;

    /** Creates a new GameListResponse instance. */
    constructor($$source: Partial<GameListResponse> = {}) {
        if (!("games" in $$source)) {
            this["games"] = [];
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("has_more" in $$source)) {
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameListResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): GameListResponse {
        const $$createField0_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("games" in $$parsedSource) {
            $$parsedSource["games"] = $$createField0_0($$parsedSource["games"]);
        }
        return new GameListResponse($$parsedSource as Partial<GameListResponse>);
    }
}

export class GameMetadataFromWebVO {
    "Source": enums$0.SourceType;
    "Game": models$0.Game;
    "Tags": metadata$0.TagItem[];

    /** Creates a new GameMetadataFromWebVO instance. */
    constructor($$source: Partial<GameMetadataFromWebVO> = {}) {
        if (!("Source" in $$source)) {
            this["Source"] = enums$0.SourceType.$zero;
        }
        if (!("Game" in $$source)) {
            this["Game"] = (new models$0.Game());
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameMetadataFromWebVO instance from a string or object.
     */
    static createFrom($$source: any = {}): GameMetadataFromWebVO {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Game" in $$parsedSource) {
            $$parsedSource["Game"] = $$createField1_0($$parsedSource["Game"]);
        }
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField2_0($$parsedSource["Tags"]);
        }
        return new GameMetadataFromWebVO($$parsedSource as Partial<GameMetadataFromWebVO>);
    }
}

export class GamePlayStats {
    "game_id": string;
    "game_name": string;
    "cover_url": string;
    "is_nsfw": boolean;
    "total_duration": number;

    /** Creates a new GamePlayStats instance. */
    constructor($$source: Partial<GamePlayStats> = {}) {
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("game_name" in $$source)) {
            this["game_name"] = "";
        }
        if (!("cover_url" in $$source)) {
            this["cover_url"] = "";
        }
        if (!("is_nsfw" in $$source)) {
            this["is_nsfw"] = false;
        }
        if (!("total_duration" in $$source)) {
            this["total_duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GamePlayStats instance from a string or object.
     */
    static createFrom($$source: any = {}): GamePlayStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GamePlayStats($$parsedSource as Partial<GamePlayStats>);
    }
}

/**
 * GameReviewProviderSyncResult describes one provider's review sync outcome.
 */
export class GameReviewProviderSyncResult {
    "provider": string;
    "status": string;
    "error": string;

    /** Creates a new GameReviewProviderSyncResult instance. */
    constructor($$source: Partial<GameReviewProviderSyncResult> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameReviewProviderSyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GameReviewProviderSyncResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameReviewProviderSyncResult($$parsedSource as Partial<GameReviewProviderSyncResult>);
    }
}

/**
 * GameReviewSyncResult keeps provider outcomes separate so partial success is visible.
 */
export class GameReviewSyncResult {
    "results": GameReviewProviderSyncResult[];
    "succeeded": number;
    "failed": number;

    /** Creates a new GameReviewSyncResult instance. */
    constructor($$source: Partial<GameReviewSyncResult> = {}) {
        if (!("results" in $$source)) {
            this["results"] = [];
        }
        if (!("succeeded" in $$source)) {
            this["succeeded"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameReviewSyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GameReviewSyncResult {
        const $$createField0_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new GameReviewSyncResult($$parsedSource as Partial<GameReviewSyncResult>);
    }
}

/**
 * GameStatsRequest 游戏统计请求参数
 */
export class GameStatsRequest {
    "game_id": string;

    /**
     * week, month, all
     */
    "dimension": enums$0.Period;

    /**
     * YYYY-MM-DD (可选，不传则使用默认范围)
     */
    "start_date": string;

    /**
     * YYYY-MM-DD (可选，不传则使用默认范围)
     */
    "end_date": string;

    /** Creates a new GameStatsRequest instance. */
    constructor($$source: Partial<GameStatsRequest> = {}) {
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("dimension" in $$source)) {
            this["dimension"] = enums$0.Period.$zero;
        }
        if (!("start_date" in $$source)) {
            this["start_date"] = "";
        }
        if (!("end_date" in $$source)) {
            this["end_date"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameStatsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GameStatsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameStatsRequest($$parsedSource as Partial<GameStatsRequest>);
    }
}

export class GameTrendSeries {
    "game_id": string;
    "game_name": string;
    "points": TimePoint[];

    /** Creates a new GameTrendSeries instance. */
    constructor($$source: Partial<GameTrendSeries> = {}) {
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("game_name" in $$source)) {
            this["game_name"] = "";
        }
        if (!("points" in $$source)) {
            this["points"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameTrendSeries instance from a string or object.
     */
    static createFrom($$source: any = {}): GameTrendSeries {
        const $$createField2_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("points" in $$parsedSource) {
            $$parsedSource["points"] = $$createField2_0($$parsedSource["points"]);
        }
        return new GameTrendSeries($$parsedSource as Partial<GameTrendSeries>);
    }
}

/**
 * HeatmapCell 日级热力图单元
 */
export class HeatmapCell {
    /**
     * YYYY-MM-DD
     */
    "date": string;

    /**
     * seconds
     */
    "duration": number;

    /** Creates a new HeatmapCell instance. */
    constructor($$source: Partial<HeatmapCell> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeatmapCell instance from a string or object.
     */
    static createFrom($$source: any = {}): HeatmapCell {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeatmapCell($$parsedSource as Partial<HeatmapCell>);
    }
}

export class HikarinagiAuthStatus {
    "authorized": boolean;
    "needs_reauthorization": boolean;
    "user_id": string;
    "username": string;
    "avatar_url": string;
    "access_token_expires_at": string;
    "last_error": string;

    /** Creates a new HikarinagiAuthStatus instance. */
    constructor($$source: Partial<HikarinagiAuthStatus> = {}) {
        if (!("authorized" in $$source)) {
            this["authorized"] = false;
        }
        if (!("needs_reauthorization" in $$source)) {
            this["needs_reauthorization"] = false;
        }
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("avatar_url" in $$source)) {
            this["avatar_url"] = "";
        }
        if (!("access_token_expires_at" in $$source)) {
            this["access_token_expires_at"] = "";
        }
        if (!("last_error" in $$source)) {
            this["last_error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HikarinagiAuthStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): HikarinagiAuthStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HikarinagiAuthStatus($$parsedSource as Partial<HikarinagiAuthStatus>);
    }
}

export class HikarinagiProfile {
    "user_id": string;
    "username": string;
    "nickname": string;
    "avatar_url": string;

    /** Creates a new HikarinagiProfile instance. */
    constructor($$source: Partial<HikarinagiProfile> = {}) {
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("nickname" in $$source)) {
            this["nickname"] = "";
        }
        if (!("avatar_url" in $$source)) {
            this["avatar_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HikarinagiProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): HikarinagiProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HikarinagiProfile($$parsedSource as Partial<HikarinagiProfile>);
    }
}

export class HomePageData {
    /**
     * 上次游玩的游戏
     */
    "last_played": LastPlayedGame | null;

    /**
     * 最近游玩游戏列表
     */
    "recent_played": LastPlayedGame[];
    "today_play_time_sec": number;
    "weekly_play_time_sec": number;

    /** Creates a new HomePageData instance. */
    constructor($$source: Partial<HomePageData> = {}) {
        if (!("last_played" in $$source)) {
            this["last_played"] = null;
        }
        if (!("recent_played" in $$source)) {
            this["recent_played"] = [];
        }
        if (!("today_play_time_sec" in $$source)) {
            this["today_play_time_sec"] = 0;
        }
        if (!("weekly_play_time_sec" in $$source)) {
            this["weekly_play_time_sec"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HomePageData instance from a string or object.
     */
    static createFrom($$source: any = {}): HomePageData {
        const $$createField0_0 = $$createType21;
        const $$createField1_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("last_played" in $$parsedSource) {
            $$parsedSource["last_played"] = $$createField0_0($$parsedSource["last_played"]);
        }
        if ("recent_played" in $$parsedSource) {
            $$parsedSource["recent_played"] = $$createField1_0($$parsedSource["recent_played"]);
        }
        return new HomePageData($$parsedSource as Partial<HomePageData>);
    }
}

/**
 * HourPlayPoint 24 小时游玩时段分布
 */
export class HourPlayPoint {
    /**
     * 0~23
     */
    "hour": number;

    /**
     * seconds
     */
    "duration": number;

    /** Creates a new HourPlayPoint instance. */
    constructor($$source: Partial<HourPlayPoint> = {}) {
        if (!("hour" in $$source)) {
            this["hour"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HourPlayPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): HourPlayPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HourPlayPoint($$parsedSource as Partial<HourPlayPoint>);
    }
}

/**
 * ImportMetadataDuplicateRequest 元数据重复检查请求。
 */
export class ImportMetadataDuplicateRequest {
    "source": enums$0.SourceType;
    "source_id": string;

    /** Creates a new ImportMetadataDuplicateRequest instance. */
    constructor($$source: Partial<ImportMetadataDuplicateRequest> = {}) {
        if (!("source" in $$source)) {
            this["source"] = enums$0.SourceType.$zero;
        }
        if (!("source_id" in $$source)) {
            this["source_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportMetadataDuplicateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportMetadataDuplicateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportMetadataDuplicateRequest($$parsedSource as Partial<ImportMetadataDuplicateRequest>);
    }
}

/**
 * ImportMetadataDuplicateResult 元数据重复检查结果。
 */
export class ImportMetadataDuplicateResult {
    "source": enums$0.SourceType;
    "source_id": string;
    "exists": boolean;
    "existing_id"?: string;
    "existing_name"?: string;

    /** Creates a new ImportMetadataDuplicateResult instance. */
    constructor($$source: Partial<ImportMetadataDuplicateResult> = {}) {
        if (!("source" in $$source)) {
            this["source"] = enums$0.SourceType.$zero;
        }
        if (!("source_id" in $$source)) {
            this["source_id"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportMetadataDuplicateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportMetadataDuplicateResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportMetadataDuplicateResult($$parsedSource as Partial<ImportMetadataDuplicateResult>);
    }
}

/**
 * ImportSelection 外部导入预览中用户选择的条目。
 */
export class ImportSelection {
    "name": string;
    "path"?: string;
    "source_type"?: enums$0.SourceType;
    "source_id"?: string;

    /** Creates a new ImportSelection instance. */
    constructor($$source: Partial<ImportSelection> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportSelection instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportSelection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportSelection($$parsedSource as Partial<ImportSelection>);
    }
}

/**
 * InstallRequest 通过 lunabox://install?... 触发的安装请求
 */
export class InstallRequest {
    /**
     * 下载直链（必填）
     */
    "url": string;

    /**
     * 下载文件名（必填，不再从 URL 猜测）
     */
    "file_name": string;

    /**
     * 压缩格式：none/zip/rar/7z/tar/tar.gz/tar.bz2/tar.xz/tar.zst/tgz/tbz2/txz/tzst（必填）
     */
    "archive_format": string;

    /**
     * 启动相对路径（可选；有值时拼接下载目录作为可执行路径）
     */
    "startup_path": string;

    /**
     * 游戏标题（fallback 展示用）
     */
    "title": string;

    /**
     * 下载来源：Shionlib / Umbra 等（可选，用于用户识别）
     */
    "download_source": string;

    /**
     * 元数据来源：bangumi / vndb / ymgal / steam（可选）
     */
    "meta_source": string;

    /**
     * 元数据 ID，对应刮削源的 ID（可选）
     */
    "meta_id": string;

    /**
     * 文件大小（bytes，必填；会做强校验并限制下载上限）
     */
    "size": number;

    /**
     * 校验算法：sha256/blake3（必填）
     */
    "checksum_algo": string;

    /**
     * 校验值（64 位 hex，小写，必填）
     */
    "checksum": string;

    /**
     * 请求过期时间（Unix 秒，必填）
     */
    "expires_at": number;

    /** Creates a new InstallRequest instance. */
    constructor($$source: Partial<InstallRequest> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("file_name" in $$source)) {
            this["file_name"] = "";
        }
        if (!("archive_format" in $$source)) {
            this["archive_format"] = "";
        }
        if (!("startup_path" in $$source)) {
            this["startup_path"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("download_source" in $$source)) {
            this["download_source"] = "";
        }
        if (!("meta_source" in $$source)) {
            this["meta_source"] = "";
        }
        if (!("meta_id" in $$source)) {
            this["meta_id"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("checksum_algo" in $$source)) {
            this["checksum_algo"] = "";
        }
        if (!("checksum" in $$source)) {
            this["checksum"] = "";
        }
        if (!("expires_at" in $$source)) {
            this["expires_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallRequest($$parsedSource as Partial<InstallRequest>);
    }
}

/**
 * LastPlayedGame 上次游玩的游戏信息
 */
export class LastPlayedGame {
    "game": models$0.Game;

    /**
     * 上次游玩时间
     */
    "last_played_at": string;

    /**
     * 上次游玩时长（秒）
     */
    "last_played_dur": number;

    /**
     * 总游玩时长（秒）
     */
    "total_played_dur": number;

    /**
     * 是否正在游玩
     */
    "is_playing": boolean;

    /** Creates a new LastPlayedGame instance. */
    constructor($$source: Partial<LastPlayedGame> = {}) {
        if (!("game" in $$source)) {
            this["game"] = (new models$0.Game());
        }
        if (!("last_played_at" in $$source)) {
            this["last_played_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("last_played_dur" in $$source)) {
            this["last_played_dur"] = 0;
        }
        if (!("total_played_dur" in $$source)) {
            this["total_played_dur"] = 0;
        }
        if (!("is_playing" in $$source)) {
            this["is_playing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LastPlayedGame instance from a string or object.
     */
    static createFrom($$source: any = {}): LastPlayedGame {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("game" in $$parsedSource) {
            $$parsedSource["game"] = $$createField0_0($$parsedSource["game"]);
        }
        return new LastPlayedGame($$parsedSource as Partial<LastPlayedGame>);
    }
}

export class MetadataRefreshResult {
    "total_games": number;
    "updated_games": number;
    "skipped_games": number;
    "failed_games": number;
    "locked_games": number;
    "failed_game_ids": string[];
    "failed_game_names": string[];

    /** Creates a new MetadataRefreshResult instance. */
    constructor($$source: Partial<MetadataRefreshResult> = {}) {
        if (!("total_games" in $$source)) {
            this["total_games"] = 0;
        }
        if (!("updated_games" in $$source)) {
            this["updated_games"] = 0;
        }
        if (!("skipped_games" in $$source)) {
            this["skipped_games"] = 0;
        }
        if (!("failed_games" in $$source)) {
            this["failed_games"] = 0;
        }
        if (!("locked_games" in $$source)) {
            this["locked_games"] = 0;
        }
        if (!("failed_game_ids" in $$source)) {
            this["failed_game_ids"] = [];
        }
        if (!("failed_game_names" in $$source)) {
            this["failed_game_names"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetadataRefreshResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MetadataRefreshResult {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("failed_game_ids" in $$parsedSource) {
            $$parsedSource["failed_game_ids"] = $$createField5_0($$parsedSource["failed_game_ids"]);
        }
        if ("failed_game_names" in $$parsedSource) {
            $$parsedSource["failed_game_names"] = $$createField6_0($$parsedSource["failed_game_names"]);
        }
        return new MetadataRefreshResult($$parsedSource as Partial<MetadataRefreshResult>);
    }
}

export class MetadataRequest {
    /**
     * "bangumi" | "vndb" | "ymgal" | "steam"
     */
    "source": enums$0.SourceType;
    "id": string;

    /** Creates a new MetadataRequest instance. */
    constructor($$source: Partial<MetadataRequest> = {}) {
        if (!("source" in $$source)) {
            this["source"] = enums$0.SourceType.$zero;
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetadataRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MetadataRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetadataRequest($$parsedSource as Partial<MetadataRequest>);
    }
}

export class PeriodStats {
    /**
     * day, week, month
     */
    "dimension": enums$0.Period;

    /**
     * YYYY-MM-DD
     */
    "start_date": string;

    /**
     * YYYY-MM-DD
     */
    "end_date": string;
    "total_play_count": number;
    "total_play_duration": number;

    /**
     * 本期间内游玩过的游戏数量
     */
    "total_games_count": number;

    /**
     * 本期间内已通关游戏数量
     */
    "completed_games_count": number;

    /**
     * 库中所有游戏数量
     */
    "library_games_count": number;

    /**
     * 所有session数量
     */
    "all_sessions_count": number;

    /**
     * 所有session总时长
     */
    "all_sessions_duration": number;

    /**
     * 所有已通关游戏数量
     */
    "all_completed_games_count": number;

    /**
     * 本期间内有游玩记录的天数
     */
    "active_days": number;

    /**
     * 活跃日均时长（秒）= 总时长 / active_days
     */
    "avg_daily_duration": number;

    /**
     * 平均每次游玩时长（秒）
     */
    "avg_session_duration": number;

    /**
     * 本期间内最长连续游玩天数
     */
    "max_streak": number;

    /**
     * 至 end_date 为止的当前连续天数
     */
    "current_streak": number;

    /**
     * 本期间内新增到库中的游戏数
     */
    "new_games_count": number;
    "play_time_leaderboard": GamePlayStats[];
    "timeline": TimePoint[];
    "leaderboard_series": GameTrendSeries[];

    /**
     * Top 标签（按时长排序，已过滤剧透标签）
     */
    "tag_distribution": TagPlayStats[];

    /**
     * 年维度时填充：本期间内按日聚合
     */
    "heatmap": HeatmapCell[];

    /**
     * 24 小时游玩时段分布
     */
    "hourly_distribution": HourPlayPoint[];

    /**
     * 7 天每天分布
     */
    "weekday_distribution": WeekdayPlayPoint[];

    /** Creates a new PeriodStats instance. */
    constructor($$source: Partial<PeriodStats> = {}) {
        if (!("dimension" in $$source)) {
            this["dimension"] = enums$0.Period.$zero;
        }
        if (!("start_date" in $$source)) {
            this["start_date"] = "";
        }
        if (!("end_date" in $$source)) {
            this["end_date"] = "";
        }
        if (!("total_play_count" in $$source)) {
            this["total_play_count"] = 0;
        }
        if (!("total_play_duration" in $$source)) {
            this["total_play_duration"] = 0;
        }
        if (!("total_games_count" in $$source)) {
            this["total_games_count"] = 0;
        }
        if (!("completed_games_count" in $$source)) {
            this["completed_games_count"] = 0;
        }
        if (!("library_games_count" in $$source)) {
            this["library_games_count"] = 0;
        }
        if (!("all_sessions_count" in $$source)) {
            this["all_sessions_count"] = 0;
        }
        if (!("all_sessions_duration" in $$source)) {
            this["all_sessions_duration"] = 0;
        }
        if (!("all_completed_games_count" in $$source)) {
            this["all_completed_games_count"] = 0;
        }
        if (!("active_days" in $$source)) {
            this["active_days"] = 0;
        }
        if (!("avg_daily_duration" in $$source)) {
            this["avg_daily_duration"] = 0;
        }
        if (!("avg_session_duration" in $$source)) {
            this["avg_session_duration"] = 0;
        }
        if (!("max_streak" in $$source)) {
            this["max_streak"] = 0;
        }
        if (!("current_streak" in $$source)) {
            this["current_streak"] = 0;
        }
        if (!("new_games_count" in $$source)) {
            this["new_games_count"] = 0;
        }
        if (!("play_time_leaderboard" in $$source)) {
            this["play_time_leaderboard"] = [];
        }
        if (!("timeline" in $$source)) {
            this["timeline"] = [];
        }
        if (!("leaderboard_series" in $$source)) {
            this["leaderboard_series"] = [];
        }
        if (!("tag_distribution" in $$source)) {
            this["tag_distribution"] = [];
        }
        if (!("heatmap" in $$source)) {
            this["heatmap"] = [];
        }
        if (!("hourly_distribution" in $$source)) {
            this["hourly_distribution"] = [];
        }
        if (!("weekday_distribution" in $$source)) {
            this["weekday_distribution"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeriodStats instance from a string or object.
     */
    static createFrom($$source: any = {}): PeriodStats {
        const $$createField17_0 = $$createType24;
        const $$createField18_0 = $$createType19;
        const $$createField19_0 = $$createType26;
        const $$createField20_0 = $$createType28;
        const $$createField21_0 = $$createType30;
        const $$createField22_0 = $$createType32;
        const $$createField23_0 = $$createType34;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("play_time_leaderboard" in $$parsedSource) {
            $$parsedSource["play_time_leaderboard"] = $$createField17_0($$parsedSource["play_time_leaderboard"]);
        }
        if ("timeline" in $$parsedSource) {
            $$parsedSource["timeline"] = $$createField18_0($$parsedSource["timeline"]);
        }
        if ("leaderboard_series" in $$parsedSource) {
            $$parsedSource["leaderboard_series"] = $$createField19_0($$parsedSource["leaderboard_series"]);
        }
        if ("tag_distribution" in $$parsedSource) {
            $$parsedSource["tag_distribution"] = $$createField20_0($$parsedSource["tag_distribution"]);
        }
        if ("heatmap" in $$parsedSource) {
            $$parsedSource["heatmap"] = $$createField21_0($$parsedSource["heatmap"]);
        }
        if ("hourly_distribution" in $$parsedSource) {
            $$parsedSource["hourly_distribution"] = $$createField22_0($$parsedSource["hourly_distribution"]);
        }
        if ("weekday_distribution" in $$parsedSource) {
            $$parsedSource["weekday_distribution"] = $$createField23_0($$parsedSource["weekday_distribution"]);
        }
        return new PeriodStats($$parsedSource as Partial<PeriodStats>);
    }
}

/**
 * PeriodStatsRequest 统计请求参数
 */
export class PeriodStatsRequest {
    /**
     * day, week, month
     */
    "dimension": enums$0.Period;

    /**
     * YYYY-MM-DD (可选，不传则使用默认范围)
     */
    "start_date": string;

    /**
     * YYYY-MM-DD (可选，不传则使用默认范围)
     */
    "end_date": string;

    /** Creates a new PeriodStatsRequest instance. */
    constructor($$source: Partial<PeriodStatsRequest> = {}) {
        if (!("dimension" in $$source)) {
            this["dimension"] = enums$0.Period.$zero;
        }
        if (!("start_date" in $$source)) {
            this["start_date"] = "";
        }
        if (!("end_date" in $$source)) {
            this["end_date"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeriodStatsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PeriodStatsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PeriodStatsRequest($$parsedSource as Partial<PeriodStatsRequest>);
    }
}

/**
 * ProtocolLaunchRequest 通过 lunabox://launch?game_id=... 触发的启动请求
 */
export class ProtocolLaunchRequest {
    /**
     * 游戏库中的稳定 ID（必填）
     */
    "game_id": string;

    /**
     * 原始协议 URL（调试用途）
     */
    "raw_url"?: string;

    /** Creates a new ProtocolLaunchRequest instance. */
    constructor($$source: Partial<ProtocolLaunchRequest> = {}) {
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtocolLaunchRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ProtocolLaunchRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProtocolLaunchRequest($$parsedSource as Partial<ProtocolLaunchRequest>);
    }
}

/**
 * RemoteStatusSyncProgress describes the progress and result of uploading all
 * local game statuses for one remote metadata provider.
 */
export class RemoteStatusSyncProgress {
    "provider": string;
    "status": string;
    "current": number;
    "total": number;
    "game_name": string;
    "succeeded_games": number;
    "failed_games": number;
    "failed_game_names": string[];
    "last_error": string;

    /** Creates a new RemoteStatusSyncProgress instance. */
    constructor($$source: Partial<RemoteStatusSyncProgress> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("game_name" in $$source)) {
            this["game_name"] = "";
        }
        if (!("succeeded_games" in $$source)) {
            this["succeeded_games"] = 0;
        }
        if (!("failed_games" in $$source)) {
            this["failed_games"] = 0;
        }
        if (!("failed_game_names" in $$source)) {
            this["failed_game_names"] = [];
        }
        if (!("last_error" in $$source)) {
            this["last_error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteStatusSyncProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteStatusSyncProgress {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("failed_game_names" in $$parsedSource) {
            $$parsedSource["failed_game_names"] = $$createField7_0($$parsedSource["failed_game_names"]);
        }
        return new RemoteStatusSyncProgress($$parsedSource as Partial<RemoteStatusSyncProgress>);
    }
}

/**
 * RenderTemplateRequest 渲染模板请求
 */
export class RenderTemplateRequest {
    /**
     * 模板ID
     */
    "template_id": string;

    /**
     * 导出数据
     */
    "data": StatsExportData;

    /** Creates a new RenderTemplateRequest instance. */
    constructor($$source: Partial<RenderTemplateRequest> = {}) {
        if (!("template_id" in $$source)) {
            this["template_id"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = (new StatsExportData());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenderTemplateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RenderTemplateRequest {
        const $$createField1_0 = $$createType35;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField1_0($$parsedSource["data"]);
        }
        return new RenderTemplateRequest($$parsedSource as Partial<RenderTemplateRequest>);
    }
}

/**
 * RenderTemplateResponse 渲染模板响应
 */
export class RenderTemplateResponse {
    /**
     * 渲染后的HTML
     */
    "html": string;

    /** Creates a new RenderTemplateResponse instance. */
    constructor($$source: Partial<RenderTemplateResponse> = {}) {
        if (!("html" in $$source)) {
            this["html"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenderTemplateResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): RenderTemplateResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenderTemplateResponse($$parsedSource as Partial<RenderTemplateResponse>);
    }
}

export class SaveGameFilterPresetRequest {
    "name": string;
    "tags": string[];
    "exclude_tags": boolean;
    "status": enums$0.GameStatus;
    "exclude_status": boolean;

    /** Creates a new SaveGameFilterPresetRequest instance. */
    constructor($$source: Partial<SaveGameFilterPresetRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("exclude_tags" in $$source)) {
            this["exclude_tags"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = enums$0.GameStatus.$zero;
        }
        if (!("exclude_status" in $$source)) {
            this["exclude_status"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveGameFilterPresetRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveGameFilterPresetRequest {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField1_0($$parsedSource["tags"]);
        }
        return new SaveGameFilterPresetRequest($$parsedSource as Partial<SaveGameFilterPresetRequest>);
    }
}

/**
 * StatsExportData 统计导出数据，用于模板渲染
 */
export class StatsExportData {
    /**
     * 元数据
     * 导出时间
     */
    "export_time": string;

    /**
     * 统计开始日期
     */
    "start_date": string;

    /**
     * 统计结束日期
     */
    "end_date": string;

    /**
     * 统计周期：week/month/custom
     */
    "period": string;

    /**
     * 概览数据
     * 总游玩次数
     */
    "total_play_count": number;

    /**
     * 总游玩时长（秒）
     */
    "total_play_duration": number;

    /**
     * 格式化的总游玩时长
     */
    "total_play_time_str": string;

    /**
     * 排行榜数据
     * 排行榜
     */
    "leaderboard": StatsGameItem[];

    /**
     * 图表数据（用于 Chart.js 渲染）
     * 总游玩时长时间线
     */
    "timeline": StatsTimePoint[];

    /**
     * 排行榜游戏趋势
     */
    "leaderboard_trend": StatsGameTrend[];

    /**
     * 图表标签 JSON 字符串
     */
    "chart_labels": string;

    /**
     * 图表数据 JSON 字符串
     */
    "chart_data": string;

    /**
     * 游戏趋势数据 JSON 字符串
     */
    "game_trend_data": string;

    /**
     * AI总结
     * AI总结内容
     */
    "ai_summary": string;

    /**
     * 应用信息
     * 应用名称
     */
    "app_name": string;

    /**
     * 应用版本
     */
    "app_version": string;

    /** Creates a new StatsExportData instance. */
    constructor($$source: Partial<StatsExportData> = {}) {
        if (!("export_time" in $$source)) {
            this["export_time"] = "";
        }
        if (!("start_date" in $$source)) {
            this["start_date"] = "";
        }
        if (!("end_date" in $$source)) {
            this["end_date"] = "";
        }
        if (!("period" in $$source)) {
            this["period"] = "";
        }
        if (!("total_play_count" in $$source)) {
            this["total_play_count"] = 0;
        }
        if (!("total_play_duration" in $$source)) {
            this["total_play_duration"] = 0;
        }
        if (!("total_play_time_str" in $$source)) {
            this["total_play_time_str"] = "";
        }
        if (!("leaderboard" in $$source)) {
            this["leaderboard"] = [];
        }
        if (!("timeline" in $$source)) {
            this["timeline"] = [];
        }
        if (!("leaderboard_trend" in $$source)) {
            this["leaderboard_trend"] = [];
        }
        if (!("chart_labels" in $$source)) {
            this["chart_labels"] = "";
        }
        if (!("chart_data" in $$source)) {
            this["chart_data"] = "";
        }
        if (!("game_trend_data" in $$source)) {
            this["game_trend_data"] = "";
        }
        if (!("ai_summary" in $$source)) {
            this["ai_summary"] = "";
        }
        if (!("app_name" in $$source)) {
            this["app_name"] = "";
        }
        if (!("app_version" in $$source)) {
            this["app_version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsExportData instance from a string or object.
     */
    static createFrom($$source: any = {}): StatsExportData {
        const $$createField7_0 = $$createType37;
        const $$createField8_0 = $$createType39;
        const $$createField9_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("leaderboard" in $$parsedSource) {
            $$parsedSource["leaderboard"] = $$createField7_0($$parsedSource["leaderboard"]);
        }
        if ("timeline" in $$parsedSource) {
            $$parsedSource["timeline"] = $$createField8_0($$parsedSource["timeline"]);
        }
        if ("leaderboard_trend" in $$parsedSource) {
            $$parsedSource["leaderboard_trend"] = $$createField9_0($$parsedSource["leaderboard_trend"]);
        }
        return new StatsExportData($$parsedSource as Partial<StatsExportData>);
    }
}

/**
 * StatsGameItem 统计游戏项
 */
export class StatsGameItem {
    /**
     * 排名
     */
    "rank": number;

    /**
     * 游戏ID
     */
    "game_id": string;

    /**
     * 游戏名称
     */
    "game_name": string;

    /**
     * 封面URL
     */
    "cover_url": string;

    /**
     * 封面Base64（避免CORS）
     */
    "cover_base64": string;

    /**
     * 总时长（秒）
     */
    "total_duration": number;

    /**
     * 格式化时长
     */
    "duration_str": string;

    /** Creates a new StatsGameItem instance. */
    constructor($$source: Partial<StatsGameItem> = {}) {
        if (!("rank" in $$source)) {
            this["rank"] = 0;
        }
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("game_name" in $$source)) {
            this["game_name"] = "";
        }
        if (!("cover_url" in $$source)) {
            this["cover_url"] = "";
        }
        if (!("cover_base64" in $$source)) {
            this["cover_base64"] = "";
        }
        if (!("total_duration" in $$source)) {
            this["total_duration"] = 0;
        }
        if (!("duration_str" in $$source)) {
            this["duration_str"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsGameItem instance from a string or object.
     */
    static createFrom($$source: any = {}): StatsGameItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatsGameItem($$parsedSource as Partial<StatsGameItem>);
    }
}

/**
 * StatsGameTrend 游戏趋势数据
 */
export class StatsGameTrend {
    "game_id": string;
    "game_name": string;
    "points": StatsTimePoint[];

    /**
     * 图表颜色
     */
    "color": string;

    /** Creates a new StatsGameTrend instance. */
    constructor($$source: Partial<StatsGameTrend> = {}) {
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("game_name" in $$source)) {
            this["game_name"] = "";
        }
        if (!("points" in $$source)) {
            this["points"] = [];
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsGameTrend instance from a string or object.
     */
    static createFrom($$source: any = {}): StatsGameTrend {
        const $$createField2_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("points" in $$parsedSource) {
            $$parsedSource["points"] = $$createField2_0($$parsedSource["points"]);
        }
        return new StatsGameTrend($$parsedSource as Partial<StatsGameTrend>);
    }
}

/**
 * StatsTimePoint 时间点数据
 */
export class StatsTimePoint {
    /**
     * 标签（日期）
     */
    "label": string;

    /**
     * 时长（秒）
     */
    "duration": number;

    /**
     * 格式化时长
     */
    "duration_str": string;

    /**
     * 小时数（用于图表）
     */
    "hours": number;

    /** Creates a new StatsTimePoint instance. */
    constructor($$source: Partial<StatsTimePoint> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("duration_str" in $$source)) {
            this["duration_str"] = "";
        }
        if (!("hours" in $$source)) {
            this["hours"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsTimePoint instance from a string or object.
     */
    static createFrom($$source: any = {}): StatsTimePoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatsTimePoint($$parsedSource as Partial<StatsTimePoint>);
    }
}

/**
 * TagPlayStats 标签游玩统计：本期间内某 tag 关联游戏的累计时长
 */
export class TagPlayStats {
    "name": string;

    /**
     * seconds
     */
    "total_duration": number;

    /**
     * 关联的游戏数（去重）
     */
    "game_count": number;

    /** Creates a new TagPlayStats instance. */
    constructor($$source: Partial<TagPlayStats> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("total_duration" in $$source)) {
            this["total_duration"] = 0;
        }
        if (!("game_count" in $$source)) {
            this["game_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TagPlayStats instance from a string or object.
     */
    static createFrom($$source: any = {}): TagPlayStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TagPlayStats($$parsedSource as Partial<TagPlayStats>);
    }
}

/**
 * TemplateInfo 模板信息
 */
export class TemplateInfo {
    /**
     * 模板唯一标识（文件名不含扩展名）
     */
    "id": string;

    /**
     * 模板显示名称
     */
    "name": string;

    /**
     * 模板描述
     */
    "description": string;

    /**
     * 模板作者
     */
    "author": string;

    /**
     * 模板版本
     */
    "version": string;

    /**
     * 预览图（Base64或URL）
     */
    "preview": string;

    /**
     * 是否内置模板
     */
    "is_builtin": boolean;

    /**
     * 模板文件路径
     */
    "file_path": string;

    /** Creates a new TemplateInfo instance. */
    constructor($$source: Partial<TemplateInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("preview" in $$source)) {
            this["preview"] = "";
        }
        if (!("is_builtin" in $$source)) {
            this["is_builtin"] = false;
        }
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TemplateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemplateInfo($$parsedSource as Partial<TemplateInfo>);
    }
}

export class TimePoint {
    /**
     * YYYY-MM-DD or YYYY-MM
     */
    "label": string;

    /**
     * seconds
     */
    "duration": number;

    /** Creates a new TimePoint instance. */
    constructor($$source: Partial<TimePoint> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimePoint instance from a string or object.
     */
    static createFrom($$source: any = {}): TimePoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimePoint($$parsedSource as Partial<TimePoint>);
    }
}

/**
 * UmbraUserProfile Umbra 当前授权账户信息。
 */
export class UmbraUserProfile {
    "id": string;
    "username": string;
    "quota_bytes": number;
    "used_bytes": number;
    "available_bytes": number;

    /** Creates a new UmbraUserProfile instance. */
    constructor($$source: Partial<UmbraUserProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("quota_bytes" in $$source)) {
            this["quota_bytes"] = 0;
        }
        if (!("used_bytes" in $$source)) {
            this["used_bytes"] = 0;
        }
        if (!("available_bytes" in $$source)) {
            this["available_bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UmbraUserProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): UmbraUserProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UmbraUserProfile($$parsedSource as Partial<UmbraUserProfile>);
    }
}

/**
 * WeekdayPlayPoint 7 天每天分布（0=周日 ... 6=周六，与 JS Date.getDay 对齐）
 */
export class WeekdayPlayPoint {
    /**
     * 0~6
     */
    "weekday": number;

    /**
     * seconds
     */
    "duration": number;

    /** Creates a new WeekdayPlayPoint instance. */
    constructor($$source: Partial<WeekdayPlayPoint> = {}) {
        if (!("weekday" in $$source)) {
            this["weekday"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeekdayPlayPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): WeekdayPlayPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WeekdayPlayPoint($$parsedSource as Partial<WeekdayPlayPoint>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = models$0.Game.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = metadata$0.TagItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = GameMetadataFromWebVO.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = BatchImportMetadataSourceError.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = BatchImportCandidate.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = DBBackupInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = DailyPlayTime.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Array($$createType1);
const $$createType16 = GameReviewProviderSyncResult.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = TimePoint.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = LastPlayedGame.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = $Create.Array($$createType20);
const $$createType23 = GamePlayStats.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = GameTrendSeries.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = TagPlayStats.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = HeatmapCell.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = HourPlayPoint.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = WeekdayPlayPoint.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = StatsExportData.createFrom;
const $$createType36 = StatsGameItem.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = StatsTimePoint.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = StatsGameTrend.createFrom;
const $$createType41 = $Create.Array($$createType40);
