// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Candidate {
    "path": string;
    "kind": string;
    "confidence": string;
    "score": number;
    "write_count": number;
    "modified_files": number;
    "signals": string[];
    "last_modified"?: string;
    "size"?: number;

    /** Creates a new Candidate instance. */
    constructor($$source: Partial<Candidate> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = "";
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }
        if (!("write_count" in $$source)) {
            this["write_count"] = 0;
        }
        if (!("modified_files" in $$source)) {
            this["modified_files"] = 0;
        }
        if (!("signals" in $$source)) {
            this["signals"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Candidate instance from a string or object.
     */
    static createFrom($$source: any = {}): Candidate {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("signals" in $$parsedSource) {
            $$parsedSource["signals"] = $$createField6_0($$parsedSource["signals"]);
        }
        return new Candidate($$parsedSource as Partial<Candidate>);
    }
}

export class Result {
    "candidates": Candidate[];
    "observed_events": number;
    "started_at": string;
    "ended_at": string;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("candidates" in $$source)) {
            this["candidates"] = [];
        }
        if (!("observed_events" in $$source)) {
            this["observed_events"] = 0;
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = "";
        }
        if (!("ended_at" in $$source)) {
            this["ended_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("candidates" in $$parsedSource) {
            $$parsedSource["candidates"] = $$createField0_0($$parsedSource["candidates"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Candidate.createFrom;
const $$createType2 = $Create.Array($$createType1);
