// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../enums/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class AISummaryRequest {
    /**
     * week, month, year
     */
    "dimension": string;

    /** Creates a new AISummaryRequest instance. */
    constructor($$source: Partial<AISummaryRequest> = {}) {
        if (!("dimension" in $$source)) {
            this["dimension"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISummaryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AISummaryRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AISummaryRequest($$parsedSource as Partial<AISummaryRequest>);
    }
}

/**
 * AISummaryResponse AI总结响应
 */
export class AISummaryResponse {
    "summary": string;
    "dimension": string;

    /** Creates a new AISummaryResponse instance. */
    constructor($$source: Partial<AISummaryResponse> = {}) {
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("dimension" in $$source)) {
            this["dimension"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISummaryResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): AISummaryResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AISummaryResponse($$parsedSource as Partial<AISummaryResponse>);
    }
}

/**
 * BatchImportCandidate 批量导入候选项
 */
export class BatchImportCandidate {
    /**
     * 文件夹路径
     */
    "folder_path": string;

    /**
     * 文件夹名
     */
    "folder_name": string;

    /**
     * 检测到的可执行文件列表
     */
    "executables": string[];

    /**
     * 选中的可执行文件
     */
    "selected_exe": string;

    /**
     * 用于搜索的名称（用户可编辑）
     */
    "search_name": string;

    /**
     * 是否选中导入
     */
    "is_selected": boolean;

    /**
     * 匹配到的游戏信息
     */
    "matched_game"?: models$0.Game | null;

    /**
     * 匹配来源
     */
    "match_source"?: enums$0.SourceType;

    /**
     * 匹配状态: pending, matched, not_found, error
     */
    "match_status": string;

    /** Creates a new BatchImportCandidate instance. */
    constructor($$source: Partial<BatchImportCandidate> = {}) {
        if (!("folder_path" in $$source)) {
            this["folder_path"] = "";
        }
        if (!("folder_name" in $$source)) {
            this["folder_name"] = "";
        }
        if (!("executables" in $$source)) {
            this["executables"] = [];
        }
        if (!("selected_exe" in $$source)) {
            this["selected_exe"] = "";
        }
        if (!("search_name" in $$source)) {
            this["search_name"] = "";
        }
        if (!("is_selected" in $$source)) {
            this["is_selected"] = false;
        }
        if (!("match_status" in $$source)) {
            this["match_status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchImportCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchImportCandidate {
        const $$createField2_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("executables" in $$parsedSource) {
            $$parsedSource["executables"] = $$createField2_0($$parsedSource["executables"]);
        }
        if ("matched_game" in $$parsedSource) {
            $$parsedSource["matched_game"] = $$createField6_0($$parsedSource["matched_game"]);
        }
        return new BatchImportCandidate($$parsedSource as Partial<BatchImportCandidate>);
    }
}

export class CategoryVO {
    "id": string;
    "name": string;
    "is_system": boolean;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "game_count": number;

    /** Creates a new CategoryVO instance. */
    constructor($$source: Partial<CategoryVO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("is_system" in $$source)) {
            this["is_system"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("game_count" in $$source)) {
            this["game_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CategoryVO instance from a string or object.
     */
    static createFrom($$source: any = {}): CategoryVO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CategoryVO($$parsedSource as Partial<CategoryVO>);
    }
}

/**
 * CloudBackupItem 云端备份项
 */
export class CloudBackupItem {
    /**
     * S3 对象 key
     */
    "key": string;

    /**
     * 显示名称
     */
    "name": string;

    /**
     * 文件大小
     */
    "size": number;

    /**
     * 创建时间
     */
    "created_at": time$0.Time;

    /** Creates a new CloudBackupItem instance. */
    constructor($$source: Partial<CloudBackupItem> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloudBackupItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CloudBackupItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloudBackupItem($$parsedSource as Partial<CloudBackupItem>);
    }
}

/**
 * CloudBackupStatus 云备份状态
 */
export class CloudBackupStatus {
    /**
     * 是否启用
     */
    "enabled": boolean;

    /**
     * 是否已配置
     */
    "configured": boolean;

    /**
     * 用户标识
     */
    "user_id": string;

    /**
     * 云备份提供商: s3, onedrive
     */
    "provider": string;

    /** Creates a new CloudBackupStatus instance. */
    constructor($$source: Partial<CloudBackupStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("configured" in $$source)) {
            this["configured"] = false;
        }
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloudBackupStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): CloudBackupStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloudBackupStatus($$parsedSource as Partial<CloudBackupStatus>);
    }
}

/**
 * DBBackupInfo 数据库备份信息
 */
export class DBBackupInfo {
    /**
     * 备份文件路径
     */
    "path": string;

    /**
     * 显示名称
     */
    "name": string;

    /**
     * 文件大小
     */
    "size": number;

    /**
     * 创建时间
     */
    "created_at": time$0.Time;

    /** Creates a new DBBackupInfo instance. */
    constructor($$source: Partial<DBBackupInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBBackupInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DBBackupInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DBBackupInfo($$parsedSource as Partial<DBBackupInfo>);
    }
}

/**
 * DBBackupStatus 数据库备份状态
 */
export class DBBackupStatus {
    /**
     * 上次备份时间
     */
    "last_backup_time": string;

    /**
     * 备份列表
     */
    "backups": DBBackupInfo[];

    /** Creates a new DBBackupStatus instance. */
    constructor($$source: Partial<DBBackupStatus> = {}) {
        if (!("last_backup_time" in $$source)) {
            this["last_backup_time"] = "";
        }
        if (!("backups" in $$source)) {
            this["backups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBBackupStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DBBackupStatus {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("backups" in $$parsedSource) {
            $$parsedSource["backups"] = $$createField1_0($$parsedSource["backups"]);
        }
        return new DBBackupStatus($$parsedSource as Partial<DBBackupStatus>);
    }
}

export class DailyPlayTime {
    /**
     * YYYY-MM-DD
     */
    "date": string;

    /**
     * seconds
     */
    "duration": number;

    /** Creates a new DailyPlayTime instance. */
    constructor($$source: Partial<DailyPlayTime> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyPlayTime instance from a string or object.
     */
    static createFrom($$source: any = {}): DailyPlayTime {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DailyPlayTime($$parsedSource as Partial<DailyPlayTime>);
    }
}

export class GameDetailStats {
    /**
     * week, month, all
     */
    "dimension": string;

    /**
     * YYYY-MM-DD
     */
    "start_date": string;

    /**
     * YYYY-MM-DD
     */
    "end_date": string;
    "total_play_count": number;
    "total_play_time": number;
    "today_play_time": number;
    "recent_play_history": DailyPlayTime[];

    /** Creates a new GameDetailStats instance. */
    constructor($$source: Partial<GameDetailStats> = {}) {
        if (!("dimension" in $$source)) {
            this["dimension"] = "";
        }
        if (!("start_date" in $$source)) {
            this["start_date"] = "";
        }
        if (!("end_date" in $$source)) {
            this["end_date"] = "";
        }
        if (!("total_play_count" in $$source)) {
            this["total_play_count"] = 0;
        }
        if (!("total_play_time" in $$source)) {
            this["total_play_time"] = 0;
        }
        if (!("today_play_time" in $$source)) {
            this["today_play_time"] = 0;
        }
        if (!("recent_play_history" in $$source)) {
            this["recent_play_history"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameDetailStats instance from a string or object.
     */
    static createFrom($$source: any = {}): GameDetailStats {
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("recent_play_history" in $$parsedSource) {
            $$parsedSource["recent_play_history"] = $$createField6_0($$parsedSource["recent_play_history"]);
        }
        return new GameDetailStats($$parsedSource as Partial<GameDetailStats>);
    }
}

export class GameMetadataFromWebVO {
    "Source": enums$0.SourceType;
    "Game": models$0.Game;

    /** Creates a new GameMetadataFromWebVO instance. */
    constructor($$source: Partial<GameMetadataFromWebVO> = {}) {
        if (!("Source" in $$source)) {
            this["Source"] = enums$0.SourceType.$zero;
        }
        if (!("Game" in $$source)) {
            this["Game"] = (new models$0.Game());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameMetadataFromWebVO instance from a string or object.
     */
    static createFrom($$source: any = {}): GameMetadataFromWebVO {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Game" in $$parsedSource) {
            $$parsedSource["Game"] = $$createField1_0($$parsedSource["Game"]);
        }
        return new GameMetadataFromWebVO($$parsedSource as Partial<GameMetadataFromWebVO>);
    }
}

export class GamePlayStats {
    "game_id": string;
    "game_name": string;
    "cover_url": string;
    "total_duration": number;

    /** Creates a new GamePlayStats instance. */
    constructor($$source: Partial<GamePlayStats> = {}) {
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("game_name" in $$source)) {
            this["game_name"] = "";
        }
        if (!("cover_url" in $$source)) {
            this["cover_url"] = "";
        }
        if (!("total_duration" in $$source)) {
            this["total_duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GamePlayStats instance from a string or object.
     */
    static createFrom($$source: any = {}): GamePlayStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GamePlayStats($$parsedSource as Partial<GamePlayStats>);
    }
}

/**
 * GameStatsRequest 游戏统计请求参数
 */
export class GameStatsRequest {
    "game_id": string;

    /**
     * week, month, all
     */
    "dimension": enums$0.Period;

    /**
     * YYYY-MM-DD (可选，不传则使用默认范围)
     */
    "start_date": string;

    /**
     * YYYY-MM-DD (可选，不传则使用默认范围)
     */
    "end_date": string;

    /** Creates a new GameStatsRequest instance. */
    constructor($$source: Partial<GameStatsRequest> = {}) {
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("dimension" in $$source)) {
            this["dimension"] = enums$0.Period.$zero;
        }
        if (!("start_date" in $$source)) {
            this["start_date"] = "";
        }
        if (!("end_date" in $$source)) {
            this["end_date"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameStatsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GameStatsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameStatsRequest($$parsedSource as Partial<GameStatsRequest>);
    }
}

export class GameTrendSeries {
    "game_id": string;
    "game_name": string;
    "points": TimePoint[];

    /** Creates a new GameTrendSeries instance. */
    constructor($$source: Partial<GameTrendSeries> = {}) {
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("game_name" in $$source)) {
            this["game_name"] = "";
        }
        if (!("points" in $$source)) {
            this["points"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameTrendSeries instance from a string or object.
     */
    static createFrom($$source: any = {}): GameTrendSeries {
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("points" in $$parsedSource) {
            $$parsedSource["points"] = $$createField2_0($$parsedSource["points"]);
        }
        return new GameTrendSeries($$parsedSource as Partial<GameTrendSeries>);
    }
}

export class HomePageData {
    /**
     * 上次游玩的游戏
     */
    "last_played": LastPlayedGame | null;
    "today_play_time_sec": number;
    "weekly_play_time_sec": number;

    /** Creates a new HomePageData instance. */
    constructor($$source: Partial<HomePageData> = {}) {
        if (!("last_played" in $$source)) {
            this["last_played"] = null;
        }
        if (!("today_play_time_sec" in $$source)) {
            this["today_play_time_sec"] = 0;
        }
        if (!("weekly_play_time_sec" in $$source)) {
            this["weekly_play_time_sec"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HomePageData instance from a string or object.
     */
    static createFrom($$source: any = {}): HomePageData {
        const $$createField0_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("last_played" in $$parsedSource) {
            $$parsedSource["last_played"] = $$createField0_0($$parsedSource["last_played"]);
        }
        return new HomePageData($$parsedSource as Partial<HomePageData>);
    }
}

/**
 * LastPlayedGame 上次游玩的游戏信息
 */
export class LastPlayedGame {
    "game": models$0.Game;

    /**
     * 上次游玩时间
     */
    "last_played_at": string;

    /**
     * 上次游玩时长（秒）
     */
    "last_played_dur": number;

    /**
     * 总游玩时长（秒）
     */
    "total_played_dur": number;

    /**
     * 是否正在游玩
     */
    "is_playing": boolean;

    /** Creates a new LastPlayedGame instance. */
    constructor($$source: Partial<LastPlayedGame> = {}) {
        if (!("game" in $$source)) {
            this["game"] = (new models$0.Game());
        }
        if (!("last_played_at" in $$source)) {
            this["last_played_at"] = "";
        }
        if (!("last_played_dur" in $$source)) {
            this["last_played_dur"] = 0;
        }
        if (!("total_played_dur" in $$source)) {
            this["total_played_dur"] = 0;
        }
        if (!("is_playing" in $$source)) {
            this["is_playing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LastPlayedGame instance from a string or object.
     */
    static createFrom($$source: any = {}): LastPlayedGame {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("game" in $$parsedSource) {
            $$parsedSource["game"] = $$createField0_0($$parsedSource["game"]);
        }
        return new LastPlayedGame($$parsedSource as Partial<LastPlayedGame>);
    }
}

export class MetadataRequest {
    /**
     * "bangumi" or "vndb"
     */
    "source": enums$0.SourceType;
    "id": string;

    /** Creates a new MetadataRequest instance. */
    constructor($$source: Partial<MetadataRequest> = {}) {
        if (!("source" in $$source)) {
            this["source"] = enums$0.SourceType.$zero;
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetadataRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MetadataRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetadataRequest($$parsedSource as Partial<MetadataRequest>);
    }
}

export class PeriodStats {
    /**
     * day, week, month
     */
    "dimension": enums$0.Period;

    /**
     * YYYY-MM-DD
     */
    "start_date": string;

    /**
     * YYYY-MM-DD
     */
    "end_date": string;
    "total_play_count": number;
    "total_play_duration": number;
    "play_time_leaderboard": GamePlayStats[];
    "timeline": TimePoint[];
    "leaderboard_series": GameTrendSeries[];

    /** Creates a new PeriodStats instance. */
    constructor($$source: Partial<PeriodStats> = {}) {
        if (!("dimension" in $$source)) {
            this["dimension"] = enums$0.Period.$zero;
        }
        if (!("start_date" in $$source)) {
            this["start_date"] = "";
        }
        if (!("end_date" in $$source)) {
            this["end_date"] = "";
        }
        if (!("total_play_count" in $$source)) {
            this["total_play_count"] = 0;
        }
        if (!("total_play_duration" in $$source)) {
            this["total_play_duration"] = 0;
        }
        if (!("play_time_leaderboard" in $$source)) {
            this["play_time_leaderboard"] = [];
        }
        if (!("timeline" in $$source)) {
            this["timeline"] = [];
        }
        if (!("leaderboard_series" in $$source)) {
            this["leaderboard_series"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeriodStats instance from a string or object.
     */
    static createFrom($$source: any = {}): PeriodStats {
        const $$createField5_0 = $$createType12;
        const $$createField6_0 = $$createType8;
        const $$createField7_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("play_time_leaderboard" in $$parsedSource) {
            $$parsedSource["play_time_leaderboard"] = $$createField5_0($$parsedSource["play_time_leaderboard"]);
        }
        if ("timeline" in $$parsedSource) {
            $$parsedSource["timeline"] = $$createField6_0($$parsedSource["timeline"]);
        }
        if ("leaderboard_series" in $$parsedSource) {
            $$parsedSource["leaderboard_series"] = $$createField7_0($$parsedSource["leaderboard_series"]);
        }
        return new PeriodStats($$parsedSource as Partial<PeriodStats>);
    }
}

/**
 * PeriodStatsRequest 统计请求参数
 */
export class PeriodStatsRequest {
    /**
     * day, week, month
     */
    "dimension": enums$0.Period;

    /**
     * YYYY-MM-DD (可选，不传则使用默认范围)
     */
    "start_date": string;

    /**
     * YYYY-MM-DD (可选，不传则使用默认范围)
     */
    "end_date": string;

    /** Creates a new PeriodStatsRequest instance. */
    constructor($$source: Partial<PeriodStatsRequest> = {}) {
        if (!("dimension" in $$source)) {
            this["dimension"] = enums$0.Period.$zero;
        }
        if (!("start_date" in $$source)) {
            this["start_date"] = "";
        }
        if (!("end_date" in $$source)) {
            this["end_date"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeriodStatsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PeriodStatsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PeriodStatsRequest($$parsedSource as Partial<PeriodStatsRequest>);
    }
}

/**
 * RenderTemplateRequest 渲染模板请求
 */
export class RenderTemplateRequest {
    /**
     * 模板ID
     */
    "template_id": string;

    /**
     * 导出数据
     */
    "data": StatsExportData;

    /** Creates a new RenderTemplateRequest instance. */
    constructor($$source: Partial<RenderTemplateRequest> = {}) {
        if (!("template_id" in $$source)) {
            this["template_id"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = (new StatsExportData());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenderTemplateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RenderTemplateRequest {
        const $$createField1_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField1_0($$parsedSource["data"]);
        }
        return new RenderTemplateRequest($$parsedSource as Partial<RenderTemplateRequest>);
    }
}

/**
 * RenderTemplateResponse 渲染模板响应
 */
export class RenderTemplateResponse {
    /**
     * 渲染后的HTML
     */
    "html": string;

    /** Creates a new RenderTemplateResponse instance. */
    constructor($$source: Partial<RenderTemplateResponse> = {}) {
        if (!("html" in $$source)) {
            this["html"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenderTemplateResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): RenderTemplateResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenderTemplateResponse($$parsedSource as Partial<RenderTemplateResponse>);
    }
}

/**
 * StatsExportData 统计导出数据，用于模板渲染
 */
export class StatsExportData {
    /**
     * 元数据
     * 导出时间
     */
    "export_time": string;

    /**
     * 统计开始日期
     */
    "start_date": string;

    /**
     * 统计结束日期
     */
    "end_date": string;

    /**
     * 统计周期：week/month/custom
     */
    "period": string;

    /**
     * 概览数据
     * 总游玩次数
     */
    "total_play_count": number;

    /**
     * 总游玩时长（秒）
     */
    "total_play_duration": number;

    /**
     * 格式化的总游玩时长
     */
    "total_play_time_str": string;

    /**
     * 排行榜数据
     * 排行榜
     */
    "leaderboard": StatsGameItem[];

    /**
     * 图表数据（用于 Chart.js 渲染）
     * 总游玩时长时间线
     */
    "timeline": StatsTimePoint[];

    /**
     * 排行榜游戏趋势
     */
    "leaderboard_trend": StatsGameTrend[];

    /**
     * 图表标签 JSON 字符串
     */
    "chart_labels": string;

    /**
     * 图表数据 JSON 字符串
     */
    "chart_data": string;

    /**
     * 游戏趋势数据 JSON 字符串
     */
    "game_trend_data": string;

    /**
     * AI总结
     * AI总结内容
     */
    "ai_summary": string;

    /**
     * 应用信息
     * 应用名称
     */
    "app_name": string;

    /**
     * 应用版本
     */
    "app_version": string;

    /** Creates a new StatsExportData instance. */
    constructor($$source: Partial<StatsExportData> = {}) {
        if (!("export_time" in $$source)) {
            this["export_time"] = "";
        }
        if (!("start_date" in $$source)) {
            this["start_date"] = "";
        }
        if (!("end_date" in $$source)) {
            this["end_date"] = "";
        }
        if (!("period" in $$source)) {
            this["period"] = "";
        }
        if (!("total_play_count" in $$source)) {
            this["total_play_count"] = 0;
        }
        if (!("total_play_duration" in $$source)) {
            this["total_play_duration"] = 0;
        }
        if (!("total_play_time_str" in $$source)) {
            this["total_play_time_str"] = "";
        }
        if (!("leaderboard" in $$source)) {
            this["leaderboard"] = [];
        }
        if (!("timeline" in $$source)) {
            this["timeline"] = [];
        }
        if (!("leaderboard_trend" in $$source)) {
            this["leaderboard_trend"] = [];
        }
        if (!("chart_labels" in $$source)) {
            this["chart_labels"] = "";
        }
        if (!("chart_data" in $$source)) {
            this["chart_data"] = "";
        }
        if (!("game_trend_data" in $$source)) {
            this["game_trend_data"] = "";
        }
        if (!("ai_summary" in $$source)) {
            this["ai_summary"] = "";
        }
        if (!("app_name" in $$source)) {
            this["app_name"] = "";
        }
        if (!("app_version" in $$source)) {
            this["app_version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsExportData instance from a string or object.
     */
    static createFrom($$source: any = {}): StatsExportData {
        const $$createField7_0 = $$createType17;
        const $$createField8_0 = $$createType19;
        const $$createField9_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("leaderboard" in $$parsedSource) {
            $$parsedSource["leaderboard"] = $$createField7_0($$parsedSource["leaderboard"]);
        }
        if ("timeline" in $$parsedSource) {
            $$parsedSource["timeline"] = $$createField8_0($$parsedSource["timeline"]);
        }
        if ("leaderboard_trend" in $$parsedSource) {
            $$parsedSource["leaderboard_trend"] = $$createField9_0($$parsedSource["leaderboard_trend"]);
        }
        return new StatsExportData($$parsedSource as Partial<StatsExportData>);
    }
}

/**
 * StatsGameItem 统计游戏项
 */
export class StatsGameItem {
    /**
     * 排名
     */
    "rank": number;

    /**
     * 游戏ID
     */
    "game_id": string;

    /**
     * 游戏名称
     */
    "game_name": string;

    /**
     * 封面URL
     */
    "cover_url": string;

    /**
     * 封面Base64（避免CORS）
     */
    "cover_base64": string;

    /**
     * 总时长（秒）
     */
    "total_duration": number;

    /**
     * 格式化时长
     */
    "duration_str": string;

    /** Creates a new StatsGameItem instance. */
    constructor($$source: Partial<StatsGameItem> = {}) {
        if (!("rank" in $$source)) {
            this["rank"] = 0;
        }
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("game_name" in $$source)) {
            this["game_name"] = "";
        }
        if (!("cover_url" in $$source)) {
            this["cover_url"] = "";
        }
        if (!("cover_base64" in $$source)) {
            this["cover_base64"] = "";
        }
        if (!("total_duration" in $$source)) {
            this["total_duration"] = 0;
        }
        if (!("duration_str" in $$source)) {
            this["duration_str"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsGameItem instance from a string or object.
     */
    static createFrom($$source: any = {}): StatsGameItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatsGameItem($$parsedSource as Partial<StatsGameItem>);
    }
}

/**
 * StatsGameTrend 游戏趋势数据
 */
export class StatsGameTrend {
    "game_id": string;
    "game_name": string;
    "points": StatsTimePoint[];

    /**
     * 图表颜色
     */
    "color": string;

    /** Creates a new StatsGameTrend instance. */
    constructor($$source: Partial<StatsGameTrend> = {}) {
        if (!("game_id" in $$source)) {
            this["game_id"] = "";
        }
        if (!("game_name" in $$source)) {
            this["game_name"] = "";
        }
        if (!("points" in $$source)) {
            this["points"] = [];
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsGameTrend instance from a string or object.
     */
    static createFrom($$source: any = {}): StatsGameTrend {
        const $$createField2_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("points" in $$parsedSource) {
            $$parsedSource["points"] = $$createField2_0($$parsedSource["points"]);
        }
        return new StatsGameTrend($$parsedSource as Partial<StatsGameTrend>);
    }
}

/**
 * StatsTimePoint 时间点数据
 */
export class StatsTimePoint {
    /**
     * 标签（日期）
     */
    "label": string;

    /**
     * 时长（秒）
     */
    "duration": number;

    /**
     * 格式化时长
     */
    "duration_str": string;

    /**
     * 小时数（用于图表）
     */
    "hours": number;

    /** Creates a new StatsTimePoint instance. */
    constructor($$source: Partial<StatsTimePoint> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("duration_str" in $$source)) {
            this["duration_str"] = "";
        }
        if (!("hours" in $$source)) {
            this["hours"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatsTimePoint instance from a string or object.
     */
    static createFrom($$source: any = {}): StatsTimePoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatsTimePoint($$parsedSource as Partial<StatsTimePoint>);
    }
}

/**
 * TemplateInfo 模板信息
 */
export class TemplateInfo {
    /**
     * 模板唯一标识（文件名不含扩展名）
     */
    "id": string;

    /**
     * 模板显示名称
     */
    "name": string;

    /**
     * 模板描述
     */
    "description": string;

    /**
     * 模板作者
     */
    "author": string;

    /**
     * 模板版本
     */
    "version": string;

    /**
     * 预览图（Base64或URL）
     */
    "preview": string;

    /**
     * 是否内置模板
     */
    "is_builtin": boolean;

    /**
     * 模板文件路径
     */
    "file_path": string;

    /** Creates a new TemplateInfo instance. */
    constructor($$source: Partial<TemplateInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("preview" in $$source)) {
            this["preview"] = "";
        }
        if (!("is_builtin" in $$source)) {
            this["is_builtin"] = false;
        }
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TemplateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemplateInfo($$parsedSource as Partial<TemplateInfo>);
    }
}

export class TimePoint {
    /**
     * YYYY-MM-DD or YYYY-MM
     */
    "label": string;

    /**
     * seconds
     */
    "duration": number;

    /** Creates a new TimePoint instance. */
    constructor($$source: Partial<TimePoint> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimePoint instance from a string or object.
     */
    static createFrom($$source: any = {}): TimePoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimePoint($$parsedSource as Partial<TimePoint>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = models$0.Game.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = DBBackupInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = DailyPlayTime.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = TimePoint.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = LastPlayedGame.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = GamePlayStats.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = GameTrendSeries.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = StatsExportData.createFrom;
const $$createType16 = StatsGameItem.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = StatsTimePoint.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = StatsGameTrend.createFrom;
const $$createType21 = $Create.Array($$createType20);
